### ISSUE TITLE
Newsletter 9: Coordination/Tracking

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#111]
Feel free to suggest sections.

If you want to help writing the newsletter:

- grab one of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter, please.
  - Hard-wrap at 80 chars, please.
  - Use third-person pronouns even if you write about your project updates.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #75)
  - Mention this issue in your PR's description to link it all together.

I'm hoping to release this newsletter in the beginning of the next week, so a soft deadline for all section PRs is Sunday.

Current structure/status (I'll try to keep this updated):

- [x] DungeonFog job offer ([1](https://dungeonfog.com/about/job-offers), [2](https://www.reddit.com/r/rust/comments/g6v98u/official_rrust_whos_hiring_thread_for_jobseekers/foczm7c/)) - ✔️ done by @ozkriff in #124
- [x] London GameDev Meetup ([1](https://youtube.com/watch?v=o9QeKfKLXXM)) - ✔️ done by @ozkriff in #124
- [x] Game Updates
  - [x] CrateBeforeAttack - ✔️ done by @ozkriff in #125
  - [x] Veloren ([1](https://veloren.net/)) - ✔️ done by @AngelOnFira in #133
  - [x] Citybound Livestreams ([1](https://youtube.com/watch?v=fQMxVV57wzg), [2](https://youtube.com/watch?v=8DevxAYw47A)) - ✔️ done by @Uriopass in #119
  - [x] A/B Street ([1](https://reddit.com/r/Citybound/comments/g1k6du/rust_meetup_talk_on_ab_street), [2](https://reddit.com/r/abstreet), [2](https://reddit.com/r/rust/comments/fejx5a/demo_of_a_new_gui_2d_drawing_crate)) - ✔️ done by @Uriopass in #119
  - [x] Scale ([1](https://youtube.com/watch?v=QXF1-1BNddM), [2](http://douady.paris/blog/scale_3.html)) - ✔️ done by @Uriopass in #119
  - [x] Conquest ([1](https://twitter.com/takeryo_eeic/status/1246189179467214850), [2](https://twitter.com/takeryo_eeic/status/1249850460678193152)) - ✔️ done by @ozkriff in #125
  - [x] For the Quest ([1](https://twitter.com/seratonik/status/1246626792850329600), [2](https://twitter.com/seratonik/status/1247705152376586240), [3](https://twitter.com/seratonik/status/1249907910471061504)) - ✔️ done by @seratonik in #123
  - [x] Colony Genesis ([1](https://nativesystems.itch.io/colony/devlog/135956/colony-genesis-v103-alpha), [2](https://nativesystems.itch.io/colony/devlog/139741/colony-genesis-v104-alpha)) - ✔️ done by @ozkriff in #126
  - [x] Akigi ([1](https://devjournal.akigi.com)) - ✔️ done by @ozkriff in #125
  - [x] Blobs'n'Bullets ([1](https://twitter.com/rhmoller/status/1254179448586481669)) - ✔️ done by @ozkriff in #125
  - [x] realm.one - ✔️ done by @Machine-Hum in #128
  - [x] Big AB Games ([1](https://twitter.com/bigabgames/status/1247656705598590978), [2](https://crates.io/crates/ab_glyph_rasterizer), [3](https://twitter.com/bigabgames/status/1248679307351818245), [4](https://twitter.com/bigabgames/status/1254009409417641984)) - ✔️ done by @ozkriff in #126
  - [x] ssshmup ([1](https://github.com/mkhan45/ssshmup), [2](https://reddit.com/r/rust_gamedev/comments/g6uwah/super_small_shootem_up_using_ggez_and_specs)) - ✔️ done by @ozkriff in #126
  - [x] Amethyst Games ([1](https://twitter.com/JeremyThulliez/status/1255042737579134977), [2](https://www.wootlab.io/blog/pong-in-rust-with-amethyst), [3](https://twitter.com/JeremyThulliez/status/1251903725276454913), [4](https://reddit.com/r/rust_gamedev/comments/fwf5gk/boulder_dash_remake_using_amethyst), [5](https://azriel.im/will/2020/04/24/browsers-assemble/)) - ✔️ done by @azriel91 in #130
  - [x] Ludum Dare 46 - ([1](https://github.com/Noah2610/LD46-TheHum), [2](https://ldjam.com/events/ludum-dare/46/the-last-ship), [3](https://twitter.com/healthire_/status/1251873979305951237), [4](https://ldjam.com/events/ludum-dare/46/woods), [5](https://kettlecorn.itch.io/wonder), [6](https://twitter.com/kettlecorn/status/1251604524457881602), [7](https://twitter.com/dooskington/status/1252253239023513609), [8](https://ldjam.com/events/ludum-dare/46/fermi-paradox), **got any more?**) - ✔️ done by @Dooskington
- [x] Library & Tooling Updates
  - [x] "Measuring build timings with mathbench" ([1](https://bitshifter.github.io/2020/04/12/mathbench-build-timings)) - ✔️ done by @ozkriff in #131
  - [x] "A tutorial on/in/about/with 3D graphics, Rust, Vulkan, ash" ([1](https://reddit.com/r/rust/comments/g7pypb/3d_graphics_rust_vulkan_ash)) - ✔️ done by @ozkriff in #131
  - [x] "Implementing a linear Quadtree in Rust" ([1](https://snorrwe.onrender.com/posts/morton-table), [2](https://reddit.com/r/rust/comments/g69hgg/ive_published_my_first_blog_post_implementing_a)) - ✔️ done by @ozkriff in #131
  - [x] Multiple ECS in my personal game project ([1](https://dasifefe.com/post-2020-04-05-01.html)) - ✔️ done by @ozkriff in #131
  - [x] "Simple 2Dcamera system for Rust with GGEZ" ([1](https://dev.to/sobertkaos/simple-2dcamera-system-for-rust-with-ggez-2o2h)) - ✔️ done by @ozkriff in #131
  - [x] "Symmetric Matrices & Triangle Numbers" ([1](https://anthropicstudios.com/2020/03/30/symmetric-matrices)) - ✔️ done by @ozkriff in #131
  - [x] "Our backend – Technology" ([1](https://visarcana.com/2020/04/24/our-backend-technology)) - ✔️ done by @ozkriff in #135
  - [x] bracket-lib & roguelike book ([1](https://reddit.com/r/rust_gamedev/comments/fz5rb7/bracketlib_work_week_of_4112020_080_has_shipped), [2](https://twitter.com/herberticus/status/1252335121258237953), [3](https://drmelon.itch.io/officerl)) - ✔️ done by @17cupsofcoffee in #134
  - [x] miniquad ([1](https://not-fl3.github.io/miniquad-samples/ui.html), [2](https://patreon.com/posts/35870934), [3](https://twitter.com/fedor_games/status/1250976351328382980)) - ✔️ done by @not-fl3 in #118
  - [x] gfx/wgpu ([1](https://reddit.com/r/rust/comments/fvzmi0/wgpu05_release_changelog), [2](https://www.falseidolfactory.com/2020/04/01/intro-to-gfx-hal-part-1-drawing-a-triangle.html), [3](https://www.falseidolfactory.com/2020/04/01/intro-to-gfx-hal-part-2-push-constants.html), [4](https://www.falseidolfactory.com/2020/04/16/intro-to-gfx-hal-part-3-vertex-buffers.html), [5](https://reddit.com/r/rust/comments/g5sfth/wgpurs_on_the_web), [5](https://hacks.mozilla.org/2020/04/experimental-webgpu-in-firefox/)) - ✔️ done by @kvark in #116
  - [x] Oxygengine ([1](https://reddit.com/r/rust/comments/g5u7dw/ignite_ide_got_new_code_editor_and_media_player), [2](https://reddit.com/r/rust_gamedev/comments/g5u7e3/ignite_ide_got_new_code_editor_and_media_player), [3](https://reddit.com/r/rust_gamedev/comments/fzpeya/play_mode_window_is_now_part_of_the_ignite_game), [4](https://reddit.com/r/rust_gamedev/comments/g26ge3/proc_macro_that_builds_types_info_at_compile_time), [5](https://reddit.com/r/rust_gamedev/comments/fuobzd/ive_made_a_templates_engine_to_ease_writing)) - ✔️ done by @PsichiX in #127
  - [x] erupt v0.1 ([1](https://reddit.com/r/rust/comments/g1tqh3/erupt_vulkan_api_bindings_v010_released)) - ✔️ done by @Friz64 in #117
  - [x] Amethyst ([1](https://twitter.com/cuberoo_/status/1247562898358009859), [2](https://reddit.com/r/rust_gamedev/comments/g7xbz9/rust_amethyst_pokemon_gold), [3](https://reddit.com/r/rust_gamedev/comments/g3zwcl/fail_amethyst_engine_for_the_gameshell), [4](https://azriel.im/will/2020/04/24/browsers-assemble/)) - ✔️ done by @azriel91 in #130
  - [x] Tetra ([1](https://twitter.com/17cupsofcoffee/status/1246407935980339200), [2](https://twitter.com/17cupsofcoffee/status/1249410227935510536), [3](https://twitter.com/17cupsofcoffee/status/1254076418365030400), [4](https://twitter.com/17cupsofcoffee/status/1255901557322928128)) - ✔️ done by @17cupsofcoffee in #113
  - [x] Mun - ✔️ done by @Wodann in #120
  - [x] turbulence, goggles ([1](https://reddit.com/r/rust_gamedev/comments/fzuv71/two_new_gamedev_libraries_turbulence_and_goggles), [2](https://reddit.com/r/rust/comments/g545jz/rlua_needs_maintainers)) - ✔️ done @ozkriff in #135
  - [x] Valora ([1](https://paytonturnage.gitbook.io/valora/)) - ✔️ done by @ozkriff in #135
  - [x] dathos-game-engine ([1](https://twitter.com/resinten/status/1255697868104531968), [2](https://github.com/BrianMWest/melody-madness)) - ✔️ done by @17cupsofcoffee in #134
  - [x] shipyard v0.4 ([1](https://reddit.com/r/rust/comments/g82tza/shipyard_04_release)) - ✔️ done by @leudz in #114
  - [x] Sokoban tutorial - - ✔️ done by @iolivia in #122
  - [x] usfx ([1](https://crates.io/crates/usfx)) - ✔️ done by @PatrickHoward in #137
  - [x] iced v0.1 ([1](https://github.com/hecrj/iced/pull/253), [2](https://www.reddit.com/r/rust/comments/ftpld3/iced_a_crossplatform_gui_library_new_release/)) - ✔️ done by @PatrickHoward in #137
  - [x] asset_manger v0.2 ([1](https://reddit.com/r/rust_gamedev/comments/gadq3i/asset_manager_022)) - ✔️ done by @PatrickHoward in #137
  - [x] sarekt ([1](http://crates.io/crates/sarekt), [2](https://reddit.com/r/rust/comments/fxyjmi/have_a_look_at_this_renderer_im_working_on)) - ✔️ done by @17cupsofcoffee in #132
  - [x] Godot - ✔️ done by @17cupsofcoffee in #132
    - [x] Tutorial videos by schr3da ([1](https://youtube.com/watch?v=qEHrRLLYc3Q), [2](https://youtube.com/watch?v=aMaT6pyDocg), [3](https://youtube.com/watch?v=_Lxr6pAXBsQ), [4](https://youtube.com/watch?v=McNgUqzmQkk), [5](https://youtube.com/watch?v=SIesTvp_ZD8), [6](https://youtube.com/watch?v=GKIUWbW4G9o), [7](https://youtube.com/watch?v=_n_5MDEquk4))
    - [x] "Using Rust + Godot + Legion" ([1](https://reddit.com/r/rust_gamedev/comments/g2avzc/using_rust_godot_legion))
    - [x] "Hagsteel - A tutorial for Linux GameDevs" ([1](https://reddit.com/r/rust_gamedev/comments/g126es/godot_rust_hagsteel_a_tutorial_for_linux_gamedevs))
- [x] Bonus - ✔️ done by @ozkriff in #135

Final steps:

- [x] final review - everyone
- [x] publish - @ozkriff
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev - @ozkriff
- [x] add comment links - @ozkriff
- [x] add a draft of the 10 newsletter - @ozkriff

**Comment by seratonik** [comment]
I'll take the For The Quest section again!

**Comment by cdbattags** [comment]
I'll take Amethyst 4 (https://azriel.im/will/2020/04/24/browsers-assemble/)!

**Comment by ozkriff** [comment]
@cdbattags note that Amethyst's section is supposed to be a list of items like https://rust-gamedev.github.io/posts/newsletter-008/#amethyst

**Comment by Uriopass** [comment]
I'll take Citybound, A/B street and Scale :-) City sims are cool !

**Comment by Dooskington** [comment]
I'll take the Ludum Dare 46 games section!

**Comment by AngelOnFira** [comment]
:100: I'm good for Veloren, and I'll probably grab a few others tomorrow :ok_hand: :

**Comment by azriel91** [comment]
Heya, I'm *super* busy right now, but am asking in the Amethyst discord for help to write the content :memo:.

@cdbattags If you'd like to make a start (even just for Will), that would be helpful.

I may spare Sunday evening to review / amend the Amethyst content.

**Comment by Machine-Hum** [comment]
I know it's not currently listed, but I could do something for realm.one by the end of this weekend :)

**Comment by ozkriff** [comment]
Taking Colony Genesis, Life, Recall Singularity, Big AB Games, and ssshmup

**Comment by ozkriff** [comment]
Ugh, I'm so slow.

Taking  "Measuring build timings with mathbench",  "A tutorial on/in/about/with 3D graphics, Rust, Vulkan, ash",  "Implementing a linear Quadtree in Rust",  "Multiple ECS in my personal game project",  "Simple 2Dcamera system for Rust with GGEZ", and "Symmetric Matrices & Triangle Numbers".

**Comment by PatrickHoward** [comment]
I'll take on usfx, iced, and asset_manager!

**Comment by azriel91** [comment]
Taking on Amethyst games and library updates.

cc: @cdbattags

**Comment by 17cupsofcoffee** [comment]
I'll take sarekt and the Godot section, if no-one else is picking those up.

**Comment by ozkriff** [comment]
Grabbing "Our backend – Technology, surfman, turbulence-goggles-rlua, and Valora

**Comment by 17cupsofcoffee** [comment]
Picking up bracket-lib and dathos-game-engine to round off the list 😄

**Comment by ozkriff** [comment]
Yay, we're ready for the final PR!  #138 (_"Newsletter 9"_) - everyone is invited to review.

:timer_clock: Hope to merge this today +- at 17:00 UTC (in 10 hrs from now).

**Comment by ozkriff** [comment]
https://rust-gamedev.github.io/posts/newsletter-009

Many thanks to all contributors and reviewers! :)

**Comment by Wodann** [comment]
Nice work on the coordination again! 👏🏻

To reduce workload towards the end of the month, maybe it's an idea to open up the new coordination issue straight after releasing a new newsletter? Then people can start adding news throughout the month.

**Comment by PatrickHoward** [comment]
I actually really like that idea, maybe have like a freeze date for when things can be added

**Comment by ozkriff** [comment]
Done, sorry for the delay.

> To reduce workload towards the end of the month, maybe it's an idea to open up the new coordination issue straight after releasing a new newsletter? Then people can start adding news throughout the month.

@Wodann Well, the first step of the newsletter creation workflow (see this repo's readme) says

> At the beginning of the month, a draft of the newsletter is created from a template.

so I was supposed to add a draft anyway for people to send PRs. If you think that creating an empty coordination issue will help, why not. I'll add an outline it in ~two weeks.

**Comment by ozkriff** [comment]
Next: #139 (_"Newsletter 10: Coordination/Tracking"_)
