### ISSUE TITLE
Newsletter 10: Coordination/Tracking

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#139]
Feel free to suggest sections.

If you want to help writing the newsletter:

- grab one of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter, please.
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Use third-person pronouns even if you write about your project updates.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #75)
  - Mention this issue in your PR's description to link it all together.

~~I'm hoping to release this newsletter in the middle of the next week, so a soft deadline for all section PRs is Wednesday.~~
Ok, now I'm hoping to have a final fraft on Sunday and publish it on Monday.

Current structure/status (I'll try to keep this updated):

- [x] ToC (top-level?) - ✔️ done by @ozkriff in #156
- [x] Game Updates
  - [x] Veloren ([1](https://veloren.net)) - ✔️ done by @AngelOnFira in #145
  - [x] CrateBeforeAttack ([1](https://cratebeforeattack.com/posts/20200502-rust), [2](https://cratebeforeattack.com/posts/20200503-release-alpha-1), [3](https://cratebeforeattack.com/posts/20200516-update-alpha-3), [4](https://cratebeforeattack.com/posts/20200524-update-alpha-4)) - ✔️ done by @koalefant in #152
  - [x] Garden ([1](https://cyberplant.xyz/posts/may)) - ✔️ done by @ozkriff in #158
  - [x] orb.farm ([1](https://reddit.com/r/rust/comments/gm4whz/orbfarm_a_virtual_aquatic_ecosystem_implemented/)) - ✔️ done by @ozkriff in #158
  - [x] On FPS Game Progress: \#1 ([1](http://atilkockar.com/on-fps-game-progress-1/)) - ✔️ done by @ozkriff in #158
  - [x] Stellary ([1](https://coffejunkstudio.itch.io/stellary), [2](https://twitter.com/CoffeJunkStudio/status/1262339528964149255)) - ✔️ done by @ozkriff in #158
  - [x] Akigi ([1](https://devjournal.akigi.com)) - ✔️ done by @AngelOnFira in #157
  - [x] sandbox - ✔️ done by @JMS55 in #146
  - [x] Paddlers \#4 Benefits of full-stack Rust ([1](https://www.jakobmeier.ch/blogging/Paddlers_4.html), [2](https://reddit.com/r/rust/comments/gjilkn/benefits_of_fullstack_rust_my_experience_from)) - ✔️ done by @jakmeier in #151
  - [x] Mind's Eye ([1](https://www.reddit.com/r/rust_gamedev/comments/gnlvt1/minds_eye_a_sokubanesque_game_made_in_rust)) - ✔️ done by @ozkriff in #165
  - [x] digescape ([1](https://tantandev.itch.io/digescape), [2](https://github.com/TanTanDev/DigEscape), [3](https://youtube.com/watch?v=6fKt6bmnAKo), [4](https://youtube.com/watch?v=q6-f63vZW8Y), [5](https://youtube.com/watch?v=nKYVRcPBAog), [6](https://youtube.com/watch?v=ag3hoNo75F0)) - ✔️ done by @AngelOnFira in #155
  - [x] Sailing Simulator Prototype ([1](https://twitter.com/KunosStefano/status/1256624643122892800), [2](https://twitter.com/KunosStefano/status/1257299250171588608), [3](https://twitter.com/KunosStefano/status/1258755105970630657), [4](https://twitter.com/KunosStefano/status/1259834478798745602), [5](https://twitter.com/KunosStefano/status/1261724500510543872), [6](https://twitter.com/KunosStefano/status/1261975508100800512), [7](https://twitter.com/KunosStefano/status/1263849643009507332), [8](https://twitter.com/KunosStefano/status/1265620312919617540)) - ✔️ done by @kunos in #147
  - [x] For the Quest ([1](https://twitter.com/seratonik/status/1259957942415093761), [2](https://twitter.com/seratonik/status/1260001036472733696), [3](https://twitter.com/seratonik/status/1260285046612619265), [4](https://twitter.com/seratonik/status/1260321869003030528), [5](https://twitter.com/seratonik/status/1260763201118953472), [6](https://twitter.com/seratonik/status/1262156091766394880)) - ✔️ done by @seratonik in #149
  - [x] datoh's Life ([1](https://datoh.itch.io/life), [2](https://twitter.com/datoh/status/1264574784769318915)) - ✔️ done by @ozkriff in #165
  - [x] vkeyes-demo-rs ([1](https://github.com/funmaker/vkeyes-demo-rs)) - ✔️ done by @ozkriff in #165
  - [x] nox futura ([1](https://www.reddit.com/r/roguelikedev/comments/gg4qx4/sharing_saturday_310/fq0cvrm/), [2](https://www.reddit.com/r/roguelikedev/comments/gout79/sharing_saturday_312/frjozbb/)) - ✔️ done by @ozkriff in #166
- [x] Learning Material Updates
  - [x] Sokoban Tutorial - ✔️ done by @iolivia in #143
  - [x] Adding WASM Support to a Native Apps ([1](https://twitter.com/im_azriel/status/1258546537912627200), [2](https://azriel.im/wasm_it/), [3](https://www.youtube.com/watch?v=7YQGwb4_AvA)) - ✔️ done by @azriel91 in #153
  - [x] gfx-hal & vulkan basics ([1](https://willofindie.com/gfx-hal-initials), [2](https://twitter.com/Shub7241/status/1262217509266010113)) - ✔️ done by @ozkriff in #160
  - [x] Pong tutorial with ggez ([1](https://www.reddit.com/r/rust_gamedev/comments/go1d1z/i_tried_to_write_a_simple_pongggez_tutorial/), [2](https://mkhan45.github.io/2020/05/19/Pong-tutorial-with-ggez.html), [3](https://mkhan45.github.io/2020/05/20/Pong-tutorial-with-ggez-Part-2.html), [4](https://mkhan45.github.io/2020/05/21/Pong-tutorial-with-ggez-Part-3.html)) - ✔️ done by @ozkriff in #160
  - [x] Rust Disassembly: part 1 ([1](https://giordi91.github.io/post/disassemlbyrust1/)) ✔️ done by @giordi91 in #159
- [x] Library & Tooling Updates
  - [x] NodeFX - ([0](https://twitter.com/MrVallentin/status/1256334184492105728), [1](https://twitter.com/MrVallentin/status/1256805858022998016), [2](https://twitter.com/MrVallentin/status/1261414461115695109), [3](https://twitter.com/MrVallentin/status/1261749012962709504), [4](https://twitter.com/MrVallentin/status/1261807725928988673)) - ✔️ done by @vallentin in #154
  - [x] beehive ([1](https://github.com/toasteater/beehive), [2](https://twitter.com/toast_dev/status/1257719813696192512)) - ✔️ done by @ozkriff in #162
  - [x] rustsim survey ([1](https://twitter.com/rustsim/status/1264653224902111238), [2](https://docs.google.com/forms/d/e/1FAIpQLSes3qjVxpksw6ntendfadQW7x4MCSw6Vd2Kdg4sDFj46zs5ew/viewform), [3](https://reddit.com/r/rust/comments/gpwsk1/survey_what_do_you_need_from_a_physics_engine_in/)) - ✔️ done by @ozkriff in #162
  - [x] safe_arch ([1](https://www.reddit.com/r/rust/comments/gjvyz8/safe_arch03_is_ready_for_some_tire_kicking/)) - ✔️ done by @ozkriff in #162
  - [x] goods ([1](https://crates.io/crates/goods)) - ✔️ done by @zakarumych in #141
  - [x] svg_face ([1](https://github.com/dabreegster/svg_face)) - ✔️ done by @ozkriff in #162
  - [x] cute-c2 ([1](https://github.com/yeahross0/cute-c2)) - ✔️ done by @17cupsofcoffee in #161
  - [x] KAS v0.4 ([1](https://www.reddit.com/r/rust/comments/gf42ip/kas_gui_04_release/)) - ✔️ done by @17cupsofcoffee in #161
  - [x] rg3d engine & rusty editor - ✔️ done by @mrDIMAS in #144
  - [x] TTF Saga ([1](https://reddit.com/r/rust_gamedev/comments/gpsrkz/otf_font_rendering_or_how_i_should_have_learned/), [2](https://twitter.com/bigabgames/status/1258866371024293890), [3](https://twitter.com/bigabgames/status/1264235900462075906), [4](https://twitter.com/bigabgames/status/1264557215693918209)) - ✔️ done by @AngelOnFira in #164
  - ~~[ ] miniquad & macroquad ([1](https://twitter.com/fedor_games/)) - 🚧 WIP by @not-fl3~~
  - [x] Point of WebGPU on native ([1](http://kvark.github.io/web/gpu/native/2020/05/03/point-of-webgpu-native.html), discussions?) - ✔️ done by @ozkriff in #166
  - [x] Oxygengine ([1](https://reddit.com/r/rust_gamedev/comments/ge8tj1/yeah_i_know_its_not_comic_sans_but_at_least_i_can), [2](https://www.reddit.com/r/rust/comments/gbahqx/can_i_make_pokemon_gold_in_10_minutes_with/)) - ✔️ done by @PsichiX in #163
  - [x] Amethyst ([1](https://www.reddit.com/r/rust/comments/gcoipo/rlua_is_now_part_of_the_amethyst_organisation), [2](https://community.amethyst.rs/t/announcing-a-new-multi-tasking-library-for-legion-ecs/1495), ??) - ✔️ done by by @azriel91 in #153
  - [x] Tetra - ✔️ done by @17cupsofcoffee in #142
  - [x] Iced ([1](https://twitter.com/hecrj/status/1256347183793790977)) - ✔️ done by @ozkriff in #166
  - [x] Mun v0.2 ([1](https://mun-lang.org/blog/2020/05/16/release-mun-v0-2-0/), [2](https://reddit.com/r/rust/comments/gkzmab/mun_v020_released), [3](https://reddit.com/r/rust/comments/gj2s4s/mun_struct_hot_reloading_embedded_in_rust/)) - ✔️ done by @Wodann in #148
  - [x] Godot ([1](https://paytonrules.com/post/games-in-rust-with-godot-part-one/), [2](https://twitter.com/schreda/status/1263435929496231936), [3](https://twitter.com/toast_dev/status/1267071886040555520)) - ✔️ done by @AngelOnFira in #168
- [x] Jobs - ✔️ done by @ozkriff in #156
- [x] Bonus - ✔️ done by @ozkriff in #167

Final steps:

- [x] final review - 🚧 WIP by everyone
- [x] publish - @ozkriff
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev - @ozkriff
- [x] add comment links - @ozkriff
- [x] add a draft of the 11 newsletter - @ozkriff

**Comment by AngelOnFira** [comment]
Excited for this month! Veloren had a big release :smiley:

**Comment by kvark** [comment]
> grab one of the "free free" sections by leaving a comment

Where is the list of free sections?

For gfx-rs/wgpu this month I don't think we are going to share any updates. There is a lot going on in the pipeline, but no releases were made. cc @grovesNL

**Comment by ozkriff** [comment]
📜 Updated the structure/list of sections!

**Comment by seratonik** [comment]
I'll take care of For The Quest again :)

**Comment by kunos** [comment]
I'll work on Sailing Simulator Prototype.. but I will need a little help to understand how this works.
Am I supposed to open a PR for this and write in the "Game Updates" section directly?
https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/content/posts/newsletter-010/index.md

I'll probably wait a bit to see some games in there and copy?

**Comment by Lokathor** [comment]
Someone could add the [safe_arch 0.3 announcement](https://www.reddit.com/r/rust/comments/gjvyz8/safe_arch03_is_ready_for_some_tire_kicking/). I hope to already have a 0.4 out sometime during next month (avx2!), but the 0.3 post is relevant because I can still use more grunts to help with just the scale of the project (hundreds and hundreds of functions involved). Usability feedback (in terms of how easy it is to build abstractions on top of `safe_arch`), documentation feedback, help with PRs, etc.

**Comment by JMS55** [comment]
Hi, I'd like to add a game I've been working on, [sandbox](https://github.com/JMS55/sandbox). It's a falling sand game like sandspiel or powder toy. [Here's some gameplay showcasing a few different elements](https://streamable.com/0bhbol). The streamable link dosen't provide the best quality though, so I'm open to suggestions on where to host the video.

I'll write and overview for it and submit a PR later!

**Comment by ozkriff** [comment]
> Am I supposed to open a PR for this and write in the "Game Updates" section directly?

@kunos yep :) check PRs to the previous newsletters, like https://github.com/rust-gamedev/rust-gamedev.github.io/pull/128 for example

@Lokathor @JMS55 `safe_arch` and `sandbox` sections are added to the plan!

**Comment by ecton** [comment]
Hey @ozkriff thanks for noticing my jam project, Cosmic Cantina. I ended up getting ill at the end and honestly bit off more than I could chew too. I'm still going to be doing the essence of that project, but it's on hold for now. If you want to point people at it feel free, but it's not really an actual game at the stage the code was left at lol

Once I've gotten a bit more about my new project up and going I'll drop you a line!

**Comment by koalefant** [comment]
I will take CrateBeforeAttack.

**Comment by vallentin** [comment]
Thanks for the mention @ozkriff, I'd love to write an entry for my project. However, I'll earliest be able to do it and submit a PR on Wednesday.

**Comment by jakmeier** [comment]
I'll try to come up with something about Paddlers by today or tomorrow. Thanks for the invite/mention!

**Comment by ozkriff** [comment]
Taking "On FPS Game Progress" and "Stellary".

**Comment by ozkriff** [comment]
@ecton removed the section from the current newsletter, ping me when you feel comfortable sharing about your project! :)

**Comment by azriel91** [comment]
Heya, I'll take Adding WASM Support to a Native Apps and Amethyst :v:

**Comment by AngelOnFira** [comment]
I'll grab disescape.

**Comment by AngelOnFira** [comment]
I'll grab Akigi

**Comment by ozkriff** [comment]
Taking "gfx-hal & vulkan basics", "Pong tutorial with ggez", "beehive", "rustsim survey", "safe_arch" and "svg_face".

**Comment by 17cupsofcoffee** [comment]
Picking up 'cute-c2' and 'KAS v0.4'.

**Comment by Ratysz** [comment]
I've released a useable version of my [`yaks`](https://crates.io/crates/yaks) library (minimalistic framework for automatic multithreading of [`hecs`](https://crates.io/crates/hecs) ECS via [`rayon`](https://crates.io/crates/rayon)), is this something that has a place in the newsletter? If so, what should I do to help with that?

**Comment by ozkriff** [comment]
@Ratysz `yaks` was released today, right? Though the newsletter will be published a week later (shame on me, I'm bad at doing stuff at time), this is supposed to be a May issue that covers only what happened during that month. I've included yaks to the draft outline of the June newsletter. :)

**Comment by Ratysz** [comment]
@ozkriff the new version was released like an hour ago, yes. I'll tackle it for the June issue at some point, then. Thanks!

**Comment by ozkriff** [comment]
Taking "Mind's Eye", "datoh's Life", and "vkeyes-demo-rs".

**Comment by AngelOnFira** [comment]
Taking "beehive", "safe-arch", "svg_face", "cute_c2", and "KAS GUI"

**Comment by ozkriff** [comment]
@AngelOnFira nope, the Godot section is free atm

**Comment by ozkriff** [comment]
Taking "bracket-lib & roguelike book", "Point of WebGPU on native", "Iced"

**Comment by ozkriff** [comment]
Woo-hoo! We're ready for the final PR: #169 (_"Newsletter 10"_) - everyone is invited to review!

:timer_clock: Hope to merge this tomorrow +- at 17:00 UTC (in ~20 hrs from now).

**Comment by ozkriff** [comment]
:tada: https://rust-gamedev.github.io/posts/newsletter-010 :tada: 

A huge thanks to all contributors and reviewers! :)

**Comment by ozkriff** [comment]
Next coordination issue: #172 (_"Newsletter 11: Coordination/Tracking"_)
