### ISSUE TITLE
Newsletter 11: Coordination/Tracking

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#172]
Feel free to suggest sections!

If you want to help writing the newsletter:

- Grab one of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Mentions in brackets (like "🆓 **free** (@ozkriff ?)") are just an invitation to write the corresponding section if you want, but anyone is free to take it.
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint, please.
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Use third-person pronouns even if you write about your project updates.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #75)
  - Mention this issue in your PR's description to link it all together.

I'm hoping to release this newsletter on Monday, so a soft deadline for all section PRs is Saturday.

Current structure/status (I'll try to keep this updated):

- [x] Legion Jam ([1](https://reddit.com/r/rust_gamedev/comments/hf2n6k/where_can_i_find_rust_gamedev_jams_with_open), [2](https://reddit.com/r/rust_gamedev/comments/hggw56/i_opened_game_jam_for_ggez_legion_come)) - ✔️ done by @ozkriff in #192
- [x] Game Updates
  - [x] Way of Rhea Demo ([1](https://reddit.com/r/rust_gamedev/comments/ha9wa9/way_of_rhea_demo_steam_game_festival_game_built), [2](https://reddit.com/r/rust_gamedev/comments/hc7vex/i_just_released_a_demo_of_a_game_built_in_my_own/), [3](https://reddit.com/r/IndieDev/comments/hc7mf2/i_just_released_a_demo_of_a_game_built_in_my_own/)) - ✔️ done by @MasonRemaley in #181
  - [x] A/B Street ([1](https://youtube.com/watch?v=LxPD4n_1-LU), [2](https://reddit.com/r/Seattle/comments/hdtucd/ab_street_think_you_can_fix_seattles_traffic/), [3](https://reddit.com/r/programming/comments/he7ugs/ab_street_a_simulation_game_to_fix_seattles/)) - ✔️ done by @dabreegster in #180
  - [x] Crate Before Attack ([1](https://cratebeforeattack.com/posts/20200630-june-update/)) - ✔️ done by @koalefant in #152
  - [x] Scale ([1](https://reddit.com/r/rust_gamedev/comments/henx2n/scale_devblog_4)) - ✔️ done by @Uriopass
  - [x] Garden ([1](https://cyberplant.xyz/posts/june/), [2](https://twitter.com/logicsoup/status/1279157520767037441)) - ✔️ done by @ozkriff in #198
  - [x] Veloren ([1](https://veloren.net/), [2](https://www.gamingonlinux.com/2020/06/interviewed-veloren-an-upcoming-foss-multiplayer-voxel-rpg)) - ✔️ done by @AngelOnFira in #186
  - [x] zerotoga.me ([1](https://zerotoga.me/dev)) - ✔️ done by @ozkriff in #198
  - [x] Pont ([1](https://www.mattkeeter.com/projects/pont/)) - ✔️ done by @mkeeter in #184
  - [x] runner ([1](https://github.com/jayrave/runner)) - ✔️ done by @jayrave in #182
  - [x] Animal Chess ([1](https://reddit.com/r/rust/comments/gy7ct1/animal_fight_chess_game_written_in_rust), [2](https://github.com/netcan/AnimalChess)) - ✔️ done by @netcan in #185
  - [x] rs-type ([1](https://reddit.com/r/rust_gamedev/comments/hc9u1t/ztype_inspired_typing_first_game), [2](https://github.com/akiross/rs-type)) - ✔️ done by @ozkriff in #198
  - [x] Guacamole Runner ([1](https://twitter.com/EllenNyan0214/status/1276574981405753344)) - ✔️ done by @EllenNyan in #179
  - [x] Snake For Keyboard ([1](https://youtube.com/watch?v=OhhscXz-60g)) - ✔️ done by @TanTanDev in #187
  - [x] boundless ([1](https://www.abrigante.com/post/2020/06/04/Hello-Rust.html), [2](https://www.abrigante.com/post/2020/06/08/From-Sandbox-To-Production-Rendering.html)) - ✔️ done by @ozkriff in #198
  - [x] Weegames ([1](https://github.com/yeahross0/weegames)) - ✔️ done by @yeahross0 in #188
  - [x] blub ([1](https://github.com/wumpf/blub)) - ✔️ done by @ozkriff in #198
- [x] Learning Material Updates
  - [x] Hypervis LDN talk ([1](https://github.com/t-veor/hypervis), [2](https://youtube.com/watch?v=_22oxXEX_xc)) - ✔️ done by @ozkriff in #195
  - [x] DOOM Fire ([1](https://reddit.com/r/rust/comments/gvcj6d/doom_fire_implemented_in_rust)) - ✔️ done by @ozkriff in #195
  - [x] 3D boids ([1](https://reddit.com/r/rust/comments/gsldbi/3d_boids_swimming_along_in_perfect_harmony)) - ✔️ done by @ozkriff in #195
- [x] Library & Tooling Updates
  - [x] Rust-PSP ([1](https://reddit.com/r/rust/comments/h0izqh/announcement_rustpsp), [2](https://twitter.com/sajattack/status/1270809861983358978), [3](https://github.com/overdrivenpotato/rust-psp)) - ✔️ done by @sajattack in #183
  - [x] glam 0.9 ([1](https://twitter.com/bitshifternz/status/1277183482347708416), [2](https://crates.io/crates/glam/0.9.0)) - ✔️ done by @bitshifter in #196
  - [x] Mun ([1](https://reddit.com/r/rust/comments/h8d1vb/muns_make_it_or_break_it_contest/), [2](https://reddit.com/r/rust/comments/gzqcow/the_making_of_pong_using_mun_hot_reloading/)) - ✔️ done by @baszalmstra in #175
  - [x] GameLisp ([1](https://reddit.com/r/rust/comments/h13657/introducing_gamelisp), [2](https://reddit.com/r/lisp/comments/hf6ibn/call_for_suggestions_hotloading_in_gamelisp)) - ✔️ done by @PatrickHoward in #194
  - [x] safe_arch v0.5 - ✔️ done by @ozkriff in #200
  - [x] yaks ([1](https://crates.io/crates/yaks), [2](https://twitter.com/ratysz/status/1269291377575198721)) - ✔️ done by @Ratysz in #177
  - [x] nanoserde - ✔️ done by @not-fl3 in #197
  - [x] miniquad & macroquad - ✔️ done by @not-fl3 in #197
  - [x] Tetra ([1](https://twitter.com/17cupsofcoffee/status/1270756014472691713), [2](https://twitter.com/17cupsofcoffee/status/1275778769077317637), [3](https://twitter.com/17cupsofcoffee/status/1270043263437848578))- ✔️ done by @17cupsofcoffee in #178
  - [x] Göld ([1](https://github.com/Vurich/goeld), [2](https://reddit.com/r/rust_gamedev/comments/gwqbxl/been_working_on_a_webgpurust_reimplementation_of/)) - ✔️ done by @ozkriff in #200
  - [x] Katharos Technology & Arsenal ([1](https://katharostech.com/post/arsenal-development-now-on-github-sponsors)) - ✔️ done by @katharostech in #176
  - [x] NodeFX - ([1](https://twitter.com/MrVallentin)) - ✔️ done by @vallentin in #199
  - [x] The GC NES Emulator ([1](https://garettcooper.com/#/nes-emulator), [2](https://twitter.com/GarettWithOneR/status/1267589687473995776)) - ✔️ done by @ozkriff in #200
  - [x] Vimnail ([1](https://youtube.com/watch?v=2cSY43OcuZc)) - ✔️ done by @TanTanDev in #187
- [x] Bonus - ✔️ done by @ozkriff in #200

Final steps:

- [x] final review - by everyone
- [x] publish - @ozkriff
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev - @ozkriff
- [x] add comment links - @ozkriff
- [x] add a draft of the 12 newsletter - :heavy_check_mark: done by @ozkriff in #202

**Comment by ozkriff** [comment]
:scroll: Updated the structure/list of sections!

**Comment by Ratysz** [comment]
Taking `yaks`.

**Comment by Uriopass** [comment]
Taking `Scale` :-)

**Comment by ozkriff** [comment]
Taking Hypervis LDN talk, DOOM Fire, and 3D boids.

**Comment by PatrickHoward** [comment]
I'll nab `GameLisp`, I'll take on more if there are still more sections open later.

**Comment by netcan** [comment]
Taking `Animal Chess`

**Comment by koalefant** [comment]
I will take `Crate Before Attack`.

**Comment by dabreegster** [comment]
I'll send a PR for A/B Street later today. Thanks for organizing this!

**Comment by jakmeier** [comment]
I don't have updates for Paddlers this month. At least nothing that's ready for presenting.
(The teaser was released on the last day of May and it has already been linked in the previous newsletter)

**Comment by MasonRemaley** [comment]
I'll take `Way of Rhea`! :)

**Comment by jayrave** [comment]
I am taking `runner`

**Comment by sajattack** [comment]
I'll take rust-psp.

**Comment by mkeeter** [comment]
I'll take Pont!

**Comment by bitshifter** [comment]
I will write something about `glam` 0.9

**Comment by EllenNyan** [comment]
forgot to leave a comment, took ellen's prototype

**Comment by TanTanDev** [comment]
I'll take "Snake But I Made It For Keyboard" AND "A Mouseless Image Editor".

**Comment by ozkriff** [comment]
Sorry for the delay with reviews. 14 PRs, wow!

**Comment by ozkriff** [comment]
Taking zerotoga.me.

**Comment by ozkriff** [comment]
Ping @bitshifter @PatrickHoward @not-fl3 @vallentin. How're your sections going?

**Comment by PatrickHoward** [comment]
> 
> 
> Ping @bitshifter @PatrickHoward @koalefant @not-fl3 @vallentin. How're your sections going?

I'll have a PR for you in a few minutes

**Comment by bitshifter** [comment]
@ozkriff PR opened for the glam stuff.

**Comment by ozkriff** [comment]
Grabbing rs-type, HellBox's prototype, boundless, and Göld sections.

**Comment by ozkriff** [comment]
Any volunteers to take any of the last three free sections? :)

**Comment by vallentin** [comment]
@ozkriff been really busy, so haven't been able to see this before now.

If I can still make it, I'd be able to have a pull request ready within an hour. But to be fair, only added the SDFs and am working on GUI. So not much to add,

**Comment by ozkriff** [comment]
Taking crystal-engine and NES

**Comment by ozkriff** [comment]
The final PR: #200 (_"Newsletter 11"_) - everyone is invited to review!

:timer_clock: Hope to merge this today at ~18:00 UTC (in ~6 hrs from now).

**Comment by ozkriff** [comment]
Woo-Hoo! :tada: https://rust-gamedev.github.io/posts/newsletter-011 :tada: 

Huge thanks to all contributors and reviewers!

**Comment by ozkriff** [comment]
Next coordination issue: #201 (_"Newsletter 12: Coordination/Tracking"_)
