### ISSUE TITLE
Newsletter 12: Coordination/Tracking

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#201]
Feel free to suggest sections!

If you want to help writing the newsletter:

- Grab one of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Mentions in brackets (like "🆓 **free** (@ozkriff ?)") are just an invitation to write the corresponding section if you want, but anyone is free to take it.
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint, please.
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Use third-person pronouns even if you write about your project updates.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #75)
  - Mention this issue in your PR's description to link it all together.

I'm hoping to release this newsletter on 2020.08.03/04, so a soft deadline for all section PRs is Saturday (2020.08.01).

Current structure/status (I'll try to keep this updated):

- [x] Game Updates
  - [x] ochre 4k intro ([1](https://www.codeslow.com/2020/07/writing-winning-4k-intro-in-rust.html), [2](https://reddit.com/r/rust/comments/hlsxwg/creating_a_winning_a_4k_intro_in_rust)) - ✔️ done by @ozkriff in #255
  - [x] Robo Instructus: 1 Year Later ([1](https://blog.roboinstruct.us/2020/07/16/1-year-later.html), [2](https://reddit.com/r/rust_gamedev/comments/hsf2su/robo_instructus_1_year_later), [3](https://store.steampowered.com/newshub/app/1032170/view/4355495589078346745)) - ✔️ done by @ozkriff in #255
  - [x] Crate Before Attack ([1](https://twitter.com/CrateAttack)) - ✔️ done by @koalefant in #216
  - [x] Making a Game in 48 hours with Rust and WASM ([1](https://ianjk.com/rust-gamejam/), [2](https://www.reddit.com/r/rust/comments/hqu6dj/making_a_game_in_48_hours_with_rust_and/)) - ✔️ done by @kettle11
  - [x] unnamed multiplayer rts - ✔️ done by @pum-purum-pum-pum in #219
  - [x] A/B Street ([1](https://twitter.com/CarlinoDustin), [2](https://reddit.com/r/abstreet/)) - ✔️ done by @ozkriff in #255
  - [x] Tennis Academy Dash v0.2 ([1](https://twitter.com/oliviff/status/1285298082033348609), [2](https://twitter.com/oliviff/status/1287031044739420160)) - ✔️ done by @iolivia in #218
  - [x] protochess ([1](https://reddit.com/r/rust/comments/hki9fu/protochesscom_a_chess_website_that_lets_you_play/)) - ✔️ done by @ozkriff in #255
  - [x] Nox Futura ([1](https://twitter.com/herberticus/status/1278075371888562176)) - ✔️ done by @ozkriff in #226
  - [x] Cannon Collision ([1](https://twitter.com/thisIsRukai)) - ✔️ done by @rulai in #205
  - [x] pGLOWrpg ([1](https://twitter.com/pglowrpg)) - ✔️ done by @roalyr in #211
  - [x] text.camp ([1](https://twitter.com/textdotcamp)) - ✔️ done by @peat in #223
  - [x] Sandbox - ✔️ done by @JMS55 in #204
  - [x] Pushin' Boxes ([1](https://septum.itch.io/pushin-boxes), [2](https://septum.io/blog/my-first-game/)) - ✔️ done by @septum in #214
  - [x] Don't Stop ([1](https://reddit.com/r/rust_gamedev/comments/hq0ecp/gmtk_submission_dont_stop/)) - ✔️ done by @ozkriff in #226
  - [x] shotcaller ([1](https://github.com/amethyst/shotcaller), [2](https://twitter.com/erlend_sh/status/1287088580628709377)) - ✔️ done by @ozkriff in #226
  - [x] On FPS Game Progress: \#2 ([1](http://atilkockar.com/on-fps-game-progress-2/)) - ✔️ done by @atil in #220
  - [x] Zemeroth - ✔️ done by @ozkriff in #226
  - [x] Veloren ([1](https://veloren.net/)) - ✔️ done by @AngelOnFira in #221
- [x] Learning Material Updates
  - [x] Rust on iOS with SDL2 - ✔️ done by @aclysma in #203
  - [x] Rust Sokoban ([1](https://sokoban.iolivia.me/), [2](https://reddit.com/r/rust/comments/humqwp/learn_how_to_make_a_sokoban_game_in_rust)) - ✔️ done by @iolivia in #217
  - [x] Make Pong With RUST ([1](https://youtube.com/watch?v=TUE_HSgQiG0)) - ✔️ done by @ozkriff in #224
  - [x] An introduction to Data Oriented Design with Rust ([1](https://jamesmcm.github.io/blog/2020/07/25/intro-dod/)) - ✔️ done by @jamesmcm in #208
  - [x] "Rust'N'Games" talk by Stephan Dilly ([1](https://youtu.be/0Bj-5C2Zfqs?t=1388), [2](https://www.meetup.com/Rust-Berlin/events/272028231)) - ✔️ done by @ozkriff in #224
- [x] Library & Tooling Updates
  - [x] A Servo plugin for Unity ([1](https://blog.mozvr.com/a-browser-plugin-for-unity/), [2](https://twitter.com/mozillareality/status/1286660509077508097)) - ✔️ done by @ozkriff in #227
  - [x] big-brain ([1](https://twitter.com/zkat__/status/1281761858895048704)) - ✔️ done by @ozkriff in #227
  - [x] weasel v0.8 ([1](https://reddit.com/r/rust_gamedev/comments/hmgt6s/weasel_080_released/)) - ✔️ done by @ozkriff in #227
  - [x] naia ([1](https://github.com/naia-rs/naia), [2](https://reddit.com/r/rust/comments/hj2eey/naia_a_crossplatform_networking_library_for/)) - ✔️ done by @ozkriff in #227
  - [x] voronator ([1](https://github.com/fesoliveira014/voronator-rs), [2](https://reddit.com/r/rust/comments/hjbl0y/introducing_voronator_a_voronoi_diagram_and/)) - ✔️ done by @ozkriff in #227
  - [x] Mun - ✔️ done by @Wodann in #212
  - [x] grr 0.8 - ✔️ done by @msiglreith in #207
  - [x] miniquad & macroquad - ✔️ done by @not-fl3 in #222
  - [x] gfx/wgpu - ✔️ done by @kvark in #206
  - [x] luminance v0.40 ([1](https://phaazon.net/blog/luminance-0.40), [2](https://www.reddit.com/r/rust/comments/hsgfav/the_new_luminance_is_there/), [3](https://phaazon.net/blog/typesafe-deinterleaving)) - ✔️ done by @ozkriff in #227
  - [x] Graphene - ✔️ done by @ApoorvaJ in #210
  - [x] Vulkan Renderer by aclysma ([1](https://github.com/aclysma/renderer_prototype)) - ✔️ done by @aclysma in #203
  - [x] ludusavi ([1](https://github.com/mtkennerly/ludusavi), [2](https://reddit.com/r/rust/comments/hmv3wq/ludusavi_a_new_tool_for_backing_up_pc_game_saves), [3](https://reddit.com/r/pcgaming/comments/hmv29d/ludusavi_a_new_open_source_tool_for_backing_up), [4](https://twitter.com/mtkennerly/status/1285660672383242243)) - ✔️ done by @mtkennerly in #213
  - [x] Langcraft ([1](https://reddit.com/r/rust/comments/hx3we0/langcraft_the_llvm_target_for_minecraft), [2](https://youtube.com/watch?v=Cx0w5Wn9pPU)) - ✔️ done by @icefoxen in #209
- [x] Jobs
  - [x] Embark ([1](https://www.embark-studios.com/jobs/910166-open-source-engineer), [2](https://reddit.com/r/rust/comments/ho3z6k/job_work_on_open_source_rust_projects_at_embark), [2](https://twitter.com/AriVanider/status/1281229191711805454)) - ✔️ done by @ozkriff
- [x] Bonus - ✔️ done by @ozkriff

Final steps:

- [x] final review - ✔️ done by everyone
- [x] publish - ✔️ done by @ozkriff
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev - ✔️ done  @ozkriff
- [x] add comment links - ✔️ done by @ozkriff
- [x] add a draft of the 13 newsletter - ✔️ done by @ozkriff in #230

**Comment by ozkriff** [comment]
📜 Updated the structure/list of sections!

**Comment by ozkriff** [comment]
Does anyone know if there's a list of rusty GMTK games somewhere or something like it?

**Comment by icefoxen** [comment]
I'd like to work on `Library & Tooling Updates  - Langcraft`

**Comment by kettle11** [comment]
I'll take `Making a Game in 48 hours with Rust and WASM`. Thanks for including it!

**Comment by septum** [comment]
I'd like to work on `Pushin' Boxes`!

**Comment by roalyr** [comment]
I am taking (post-factum) `pGLOWrpg`

**Comment by mtkennerly** [comment]
Hey, I can try writing up something for Ludusavi.

**Comment by septum** [comment]
Also taking ` Voxel game prototype`.

**Comment by iolivia** [comment]
Will take a look at the ones assigned to me later today!

**Comment by ozkriff** [comment]
Ugh, the weekend wasn't nearly as productive as I planned. Well, ok, I'll be working on the newsletter all day today - the release is tomorrow. :)

**Comment by atil** [comment]
I'll take On FPS Game Progress: #2

**Comment by ozkriff** [comment]
Taking "Rust'N'Games by Stephan Dilly" and "Make Pong With RUST"

**Comment by ozkriff** [comment]
Grabbing "ochre 4k intro", "A/B Street", "protochess", "Nox Futura", and "shotcaller".

**Comment by ozkriff** [comment]
Taking "A Servo plugin for Unity", "big-brain", "weasel v0.8", "vec2d & cyclone2d", "naia"

**Comment by ozkriff** [comment]
The final PR: #229 (_"Newsletter 12"_) - everyone is invited to review :)

**Comment by ozkriff** [comment]
The newsletter has made it through its first year! Woo-Hoo!!!

:tada: https://rust-gamedev.github.io/posts/newsletter-012 :tada: 

Huge thanks to all contributors and reviewers!

**Comment by ozkriff** [comment]
Next coordination issue: #232 (_"Newsletter 13"_)
