### ISSUE TITLE
Newsletter 13

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#232]
Feel free to suggest sections!

If you want to help writing the newsletter:

- Grab one of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Mentions in brackets (like "🆓 **free** (@ozkriff ?)") are just an invitation to write the corresponding section if you want, but anyone is free to take it.
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint, please.
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Use third-person pronouns even if you write about your project updates.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #75)
  - Mention this issue in your PR's description to link it all together.

I'm hoping to release this newsletter on 2020.09.07, so a soft deadline for all section PRs is 2020.09.05.

Current structure/status (I'll try to keep this updated):

- [x] RustGameDev Podcast: two episodes ([1](https://reddit.com/r/rust_gamedev/comments/i33o6m/interview_with_team_veloren), [2](https://reddit.com/r/rust_gamedev/comments/if1esd/rustgamedev_podcast_2_herbert_wolverson), [3](https://richardpatching.com)) - ✔️ done by @icefoxen & @ozkriff in #234
- [x] Game Updates
  - [x] Crate Before Attack ([1](https://twitter.com/CrateAttack)) - ✔️ done by @koalefant in #249
  - [x] Veloren ([1](https://veloren.net/)) - ✔️ done by @AngelOnFira in #266
  - [x] A/B Street ([1](https://twitter.com/CarlinoDustin), [2](https://reddit.com/r/abstreet/)) - ✔️ done by @dabreegster in #268
  - [x] Egregoria (pka Scale) ([1](https://douady.paris/blog/egregoria_5.html)) - ✔️ done by @Uriopass in #235
  - [x] Cary ([1](https://specificprotagonist.itch.io/cary)) - ✔️ done by @SpecificProtagonist in #253
  - [x] Way of Rhea - ✔️ done by @MasonRemaley in #260
  - [x] vange-rs ([1](https://reddit.com/r/rust_gamedev/comments/i32p6r/realtime_hybrid_shadows_in_vangers), [2](https://reddit.com/r/rust_gamedev/comments/igejxy/vangers_3rd_person_camera), [3](https://www.reddit.com/r/rust_gamedev/comments/iim4f9/bar_painting_technique_in_vangers/)) - ✔️ done by @kvark in #246
  - [x] Garden ([1](https://cyberplant.xyz/posts/july-august)) - ✔️ done by @ozkriff in #273
  - [x] Chillscapes ([1](https://khonsulabs.itch.io/chillscapes), [2](https://community.khonsulabs.com/t/chillscapes-retrospective-and-kludgine-update/28)) - ✔️ done by @ecton in #258
  - [x] Dwarf Seeks Fortune ([1](https://amethyst.rs/posts/showcase-game-5-dwarf-seeks-fortune)) - ✔️ done by @Jazarro in #267
  - [x] Akigi ([1](https://devjournal.akigi.com)) - ✔️ done by @ozkriff in #270
  - [x] SIMple Physics ([1](https://reddit.com/r/rust/comments/ibk2rf/announcing_simple_physics)) -  ✔️ done by @mkhan45 in #257
- [x] Learning Material Updates
  - [x] Writing NES Emulator in Rust ([1](https://bugzmanov.github.io/nes_ebook/index.html), [2](https://twitter.com/bugzmanov/status/1292882110559195139)) - ✔️ done by @bugzmanov in #242
  - [x] "Roguelike with Amethyst" talk + blog posts ([1](https://youtube.com/watch?v=GFi_EdS_s_c), [2](https://mtigley.dev/posts/running-animation), [3](https://mtigley.dev/posts/camera-follow-system)) - ✔️ done by @tigleym in #239
  - [x] chargrid rl tutorial 2020 ([1](https://gridbugs.org/roguelike-tutorial-2020/), [2](https://twitter.com/GridSageGames/status/1295640755680112640>)) - ✔️ done by @stevebob in #240
  - [x] Event Chaining as a Decoupling Method in ECS ([1](https://www.jojolepro.com/blog/2020-08-20_event_chaining/)) - ✔️ done by @jojolepro in #265
- [x] Library & Tooling Updates
  - [x] ecs_bench_suite ([1](https://github.com/rust-gamedev/ecs_bench_suite), [2](https://reddit.com/r/rust/comments/icczxh/ecs_bench_suite_a_more_comprehensive_and), [3](https://reddit.com/r/rust_gamedev/comments/icd1eq/ecs_bench_suite_a_more_comprehensive_and), [4](https://twitter.com/rust_gamedev/status/1297926248400916483)) - ✔️ done by @ozkriff in #271
  - [x] dimforge, rapier ([1](https://twitter.com/dimforge/status/1296196116267098114), [2](https://old.reddit.com/r/rust/comments/ictbha/rustsim_becomes_dimforge_the_organization/), [3](https://reddit.com/r/rust_gamedev/comments/ictb6d/rustsim_becomes_dimforge_the_organization), [4](https://reddit.com/r/rust/comments/igkul2/announcing_rapier_2d_and_3d_physics_engines/)) - ✔️ done by @sebcrozet in #251
  - [x] cute-c2 - ✔️ done by @yeahross0 in #262
  - [x] hexasphere ([1](https://crates.io/crates/hexasphere) - ✔️ done by @OptimisticPeach in #237
  - [x] blitz-path  ([1](https://www.reddit.com/r/rust_gamedev/comments/igvf1y/blitzpath_jps_pathfinding_in_rust/)) - ✔️ done by @BezPowell in #236
  - [x] NeoCogi's libs ([1](https://github.com/NeoCogi/), [2](https://twitter.com/weloraiby/status/1288638269597638663)) - ✔️ done by @eloraiby in #243
  - [x] Mun - ✔️ done by @Wodann in #250
  - [x] inline_tweak ([1](https://crates.io/crates/inline_tweak)) - ✔️ done by @ozkriff in #271
  - [x] yacurses ([1](https://lib.rs/crates/yacurses)) - ✔️ done by @ozkriff in #271
  - [x] spir-q 0.4.2 ([1](https://www.reddit.com/r/rust_gamedev/comments/i6hxh6/spirq_042_is_now_released/)) - ✔️ done by @PENGUINLIONG in #248
  - [x] inline-spirv ([1](https://github.com/PENGUINLIONG/inline-spirv-rs), [2](https://reddit.com/r/rust_gamedev/comments/ic1005/inline_spirv_compile_and_embed_spirv)) - ✔️ done by @PENGUINLIONG in #248
  - [x] rspirv-reflect ([1](https://github.com/Traverse-Research/rspirv-reflect)) - ✔️ done by @Jasper-Bekkers in #241
  - [x] gfx/wgpu ([1](https://reddit.com/r/rust/comments/ic9e62/release_announcement_for_gfxhal06_and_wgpu06/), [2](https://www.reddit.com/r/rust_gamedev/comments/i8np5v/simplified_instancing_tutorial_learn_wgpu)) - ✔️ done by @kvark in #246
  - [x] KAS v0.5 ([1](https://old.reddit.com/r/rust/comments/i9q5nt/kas_gui_toolkit_v05)) - ✔️ done by @dhardy in 263
  - [x] egui ([1](https://github.com/emilk/egui), [2](https://github.com/emilk/hobogo), [3](https://reddit.com/r/rust/comments/hzwvsk/emigui_deserves_more_love)) - ✔️ done by @emilk in #245
  - [x] voxel-mapper ([1](https://reddit.com/r/rust_gamedev/comments/i1ktr0/smooth_voxel_mapping_a_technical_deep_dive_on), [2](https://medium.com/@bonsairobo/a-3rd-person-camera-in-complex-voxel-world-523944d5335c)) - ✔️ done by @bonsairobo in #238
  - [x] Bevy ([1](https://reddit.com/r/rust/comments/i7bcwu/introducing_bevy_a_refreshingly_simple_datadriven), [2](https://reddit.com/r/rust_gamedev/comments/i7bdqv/introducing_bevy_a_refreshingly_simple_datadriven), [3](https://reddit.com/r/rust/comments/id0qzk/scaling_bevy), [4](https://twitter.com/AmethystEngine/status/1296335581434257409), [5](https://twitter.com/dmitrywithouti/status/1296102684924219392), [6](https://twitter.com/BevyEngine)) - ✔️ done by @cart in #259
  - [x] Minigene ([1](https://git.jojolepro.com/minigene)) - ✔️ done by @jojolepro in #265
  - [x] tetra ([1](https://twitter.com/17cupsofcoffee/status/1289857217198317568), [2](https://twitter.com/17cupsofcoffee/status/1294316642680426497)) - ✔️ done by @17cupsofcoffee in #252
  - [x] Amethyst 0.15.1 ([1](https://reddit.com/r/rust/comments/ibvheq/amethyst_engine_v0151_last_specs_release)) - ✔️ done by @ozkriff in #271
  - [x] piston & nanoecs ([1](https://twitter.com/PistonDeveloper)) - ✔️ done by @bvssvni in #234
  - [x] Starframe: Architecture ([1](https://reddit.com/r/rust/comments/iju3xq/starframe_devlog_architecture_ecs_graph/)) - ✔️ done by @MoleTrooper in #256
  - [x] mochi ([1](https://github.com/richardanaya/mochi), [2](https://github.com/richardanaya/pinephone-cairo-game-starter), [3](https://reddit.com/r/rust_gamedev/comments/i2389n/how_to_build_a_pinephone_game_using_rust_cairo)) - ✔️ done by @ozkriff in #272
  - [x] Puffin Profiler ([1](https://github.com/EmbarkStudios/puffin)) - ✔️ done by @emilk in #244
  - [x] optik-rs profiler ([1](https://twitter.com/vslyusarev/status/1290814074834558976), [2](https://github.com/bombomby/optick-rs)) - ✔️ done by @ozkriff in #272
  - [x] wowAddonManager ([1](https://twitter.com/mreimsbach/status/1292427890844475393), [2](https://github.com/MR2011/wowAddonManager), [3](https://old.reddit.com/r/rust/comments/iclr6m/ive_built_a_world_of_warcraft_addon_manager)) - ✔️ done by @MR2011 in #247
  - [x] ".sia" parser & viewer ([1](https://github.com/Stromberg90/football-manager-tools)) - ✔️ done by @ozkriff in #272
  - [x] intellij-ron ([1](https://reddit.com/r/rust/comments/ictnsc/ive_created_an_free_open_source_intellij_plugin), [2](https://github.com/ron-rs/intellij-ron)) - ✔️ done by @ozkriff in #272

Final steps:

- [x] final review - 🚧 WIP by everyone
- [x] publish - @ozkriff
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev - @ozkriff
- [x] add comment links - @ozkriff
- [ ] add a draft of the 14 newsletter - @ozkriff

**Comment by ozkriff** [comment]
@icefoxen (https://github.com/rust-gamedev/rust-gamedev.github.io/issues/231):
> https://rustgamedev.com/episodes Saw this and was surprised that it wasn't included in the newsletter already, then realized it was brand new. Haven't actually listened to it yet though, so maybe it's not good. XD Will listen to it and see how it is.

**Comment by ozkriff** [comment]
📜 Updated the structure/list of sections!

**Comment by Uriopass** [comment]
I'll take Egregoria :-)

**Comment by BezPowell** [comment]
Happy to write a bit about blitz-path, I'm honoured you want to include it.

**Comment by rtsuk** [comment]
It might be better to wait to list Crankstart until the Playdate SDK is generally available. Right now it not usable by anyone who isn't in the closed developer program.

**Comment by jojolepro** [comment]
Taking: Event Chaining as a Decoupling Method in ECS
Could we also add Minigene inside of the Library & Tooling Updates section? https://github.com/jojolepro/minigene (updating the readme with more details soon)

**Comment by OptimisticPeach** [comment]
I'd be happy to write a small bit on `hexasphere`.

**Comment by tigleym** [comment]
I'd be happy to work on: "Roguelike with Amethyst" talk + blog posts .

**Comment by cwfitzgerald** [comment]
Unfortunately shader-types is fundamentally broken, and I would advice everyone not to use it. 😢

**Comment by stevebob** [comment]
Happy to write about "chargrid rl tutorial 2020"

**Comment by ecton** [comment]
@ozkriff I completed a game jam this past month and [just posted a retrospective](https://community.khonsulabs.com/t/chillscapes-retrospective-and-kludgine-update/28). If you don't mind, I'd love to write a short blurb in the Game Updates section. Figured I'd ask before sending in an unannounced PR!

**Comment by ozkriff** [comment]
@cwfitzgerald oh, ok, removed shader-types from the plan.

@rtsuk :ok_hand: sure, removed Crankstart from the current newsletter -  ping me when the SDK is released!

@jojolepro @ecton great! Added Minigene and Chillscapes sections to the plan!

**Comment by icefoxen** [comment]
I wrote up a quick thing on RustGameDev Podcast, for the second episode.  PR #234 Just added it in the "learning materials" section, but it's listed in the main issue as having its own section... where do we want to put it?

**Comment by cart** [comment]
I'll work on Bevy!

**Comment by bonsairobo** [comment]
I'll write about the smooth voxel stuff.

**Comment by PENGUINLIONG** [comment]
will take `spirq` and `inline-spirv`. thx!

**Comment by eloraiby** [comment]
Will be glad to write about NeoCogi's libs :)

**Comment by Jasper-Bekkers** [comment]
I just saw I got mentioned here for `rspirv-reflect`, I can definitely write something about that, thanks!

**Comment by bugzmanov** [comment]
Just noticed this, I'd be happy to write on "Writing NES Emulator in Rust"

**Comment by JMS55** [comment]
I'll do Sandbox

**Comment by sebcrozet** [comment]
I will take Dimforge and Rapier!

**Comment by emilk** [comment]
Thanks for the Egui mention - I've made a PR for it.

**Comment by MR2011** [comment]
I'll write about wowAddonManager

**Comment by Wodann** [comment]
Opened PR #250 to include Mun's updates in the newsletter

**Comment by AlexApps99** [comment]
Hello, I was recommended to submit this snippet of code for inclusion in the newsletter by @workingjubilee
It's an example on how to use custom panic hooks and allocation error hooks to handle panics and OOM gracefully.
[How to cleanly handle panics and OOM in a GUI application](https://users.rust-lang.org/t/how-to-cleanly-handle-panics-and-oom-in-a-gui-application/48192)

**Comment by Lokathor** [comment]
### Library & Tooling Updates
* [yacurses](https://docs.rs/yacurses) is newly released this month! It's a cross-platform curses bindings crate that's small, simple, easy to understand, and most importantly safe to use.  It wraps over `ncurses` on Unix and a bundled `pdcurses` on Windows. If you're looking to make a terminal-based roguelike (or any other terminal-based game), give it a try.

**Comment by Jazarro** [comment]
I'll write something for `Dwarf Seeks Fortune`.

**Comment by dabreegster** [comment]
Sorry for the slow response again. :(  If the deadline is still this Saturday, I can write something for A/B Street by then.

**Comment by mkhan45** [comment]
Hey, sorry I missed this. I'll try writing something for SIMple Physics

**Comment by bvssvni** [comment]
I'll write something about Piston updates, Nano-ECS and UI experiments.

**Comment by ozkriff** [comment]
> Hello, I was recommended to submit this snippet of code for inclusion in the newsletter by @workingjubilee
> It's an example on how to use custom panic hooks and allocation error hooks to handle panics and OOM gracefully.
> [How to cleanly handle panics and OOM in a GUI application](https://users.rust-lang.org/t/how-to-cleanly-handle-panics-and-oom-in-a-gui-application/48192)

@AlexApps99 sure! Added to the plan; feel free to send a PR.

**Comment by mkhan45** [comment]
If possible could you add [SIMple Mechanic's good first issues](https://github.com/mkhan45/SIMple-Mechanics/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) to the requests for contribution section?

**Comment by AlexApps99** [comment]
@ozkriff on second thought, although the example seems to work, rust-lang/rust#51245 points out that alloc functions are annotated with `#[rustc_allocator_nounwind]`, so it could potentially lead to bugs or undefined behavior.
It doesn't seem to affect Desktop platforms, but I would prefer not to recommend this until it is 100% safe.

**Comment by ozkriff** [comment]
@AlexApps99 :ok_hand:

**Comment by ozkriff** [comment]
Grabbing akigi, ecs_bench_suite, Amethyst, mochi, optik-rs, sia, aaand intellij-ron.

**Comment by ozkriff** [comment]
The final PR: #274 (_"Newsletter 13"_) - everyone is invited to review :)

**Comment by ozkriff** [comment]
:tada: https://rust-gamedev.github.io/posts/newsletter-013 :tada: 

This issue was written by more than 30 people, that's crazy! :-D
Huge thanks to all contributors and reviewers, you are awesome!

**Comment by ozkriff** [comment]
Next coordination issue: #278 (_"Newsletter 14"_)
