### ISSUE TITLE
Newsletter 14

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#278]
Feel free to suggest sections!

If you want to help writing the newsletter:

- Grab one of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just an invitation to write the corresponding section if you want, but anyone is free to take it.
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint, please.
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - Use third-person pronouns even if you write about your project updates.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #75)
  - Mention this issue in your PR's description to link it all together.

~~I'm hoping to release this newsletter on 2020.10.06, so the soft deadline for all section PRs is 2020.10.04.~~
The newsletter will be published on 2020.10.07.

Current structure/status (I'll try to keep this updated):

- [x] Game Updates
  - [x] Veloren ([1](https://veloren.net/)) - ✔️ done by @AngelOnFira in #304
  - [x] A/B Street ([1](https://twitter.com/CarlinoDustin), [2](https://reddit.com/r/abstreet/)) - ✔️ done by @dabreegster in #290
  - [x] Garden ([1](https://cyberplant.xyz/posts/september/)) - ✔️ done by @ozkriff in #313
  - [x] galangua ([1](https://github.com/tyfkda/galangua), [2](https://tyfkda.github.io/blog/2020/09/17/galangua.html)) - ✔️ done by @ozkriff in #313
  - [x] Way of Rhea - ✔️ done by @MasonRemaley in #296
  - [x] CityBound - ✔️ done by @aeplay in #294
  - [x] Recall Singularity ([1](https://reddit.com/r/rust_gamedev/comments/ilplba/the_recall_singularity_rust_godot_space_factory), [2](https://reddit.com/r/rust_gamedev/comments/imbn5q/recall_singularity_godot_rust_in_sep_2020_space)) - ✔️ done by @AngelOnFira in #305
  - [x] Nox Futura - ✔️ done by @thebracket in #303
  - [x] mimas ([1](https://github.com/est31/mimas), [2](https://github.com/est31/mimas)) - ✔️ done by @est31 in #282
  - [x] pGLOWrpg ([1](https://twitter.com/pglowrpg)) - ✔️ done by @roalyr in #291
  - [x] Oh no, Lava - ✔️ done by @troligtvis in #280
  - [x] Zemeroth ([1](https://twitter.com/ozkriff)) - ✔️ done by @ozkriff in #313
  - [x] Akigi ([1](https://devjournal.akigi.com), [2](https://reddit.com/r/rust_gamedev/comments/iwqb2i/having_fun_building_my_custom_engines)) - ✔️ done by @AngelOnFira in #307
  - [x] BUGOUT ([1](https://github.com/Terkwood/BUGOUT), [2](https://reddit.com/r/rust_gamedev/comments/ixjeoh/bugout_aidriven_multiplayer_goweiqibaduk_for_the/)) - ✔️ done by @Terkwood in #281
  - [x] Tetris Bane ([1](https://github.com/andii1701/tetris-bane), [2](https://reddit.com/r/rust_gamedev/comments/izhcz7/lockdown_side_project_tetris_bane_using_rust_with/)) - ✔️ done by @andii1701 in #299
  - [x] YAWC - ✔️ done by @junkmail22 in #301
  - [x] Space Shooter - ✔️ done by @tigleym in #298
- [x] Learning Material Updates
  - [x] Threading WGPU Resource Loading with Rayon ([1](https://sotrh.github.io/learn-wgpu/intermediate/tutorial13-threading/), [2](https://reddit.com/r/rust/comments/j16a0w/threading_wgpu_resource_loading_with_rayon), [2](https://reddit.com/r/rust/comments/iw1z6g/updated_learn_wgpu_to_06)) - ✔️ done by @ozkriff in #311
  - [x] So you want to live-reload Rust ([1](https://reddit.com/r/rust/comments/j0ajdy/so_you_want_to_livereload_rust/)) - ✔️ done by @ozkriff in #311
  - [x] rust-wasm-hotreload ([1](https://github.com/shekohex/rust-wasm-hotreload), [2](https://twitter.com/ShekoHex/status/1302973994417651714)) - ✔️ done by @ozkriff in #312
  - [x] Is it easy to draw a line ([1](https://vladjuckov.github.io/hqlines)) - ✔️ done by @pum-purum-pum-pum in #300
  - [x] An OpenGL preprocessor for Rust ([1](https://codecrash.me/an-opengl-preprocessor-for-rust)) -  ✔️ done by @krupitskas in #285
  - [x] Flappy Bird clone made with BEVY ([1](https://youtube.com/watch?v=Qjc0V58lB7A)) - ✔️ done by @AngelOnFira in #308
  - [x] Rust, gamedev, ECS, and bevy ([1](https://hugopeixoto.net/articles/rust-gamedev-ecs-bevy.html), [2](https://hugopeixoto.net/articles/rust-gamedev-ecs-bevy-p2.html)) - ✔️ done by @hugopeixoto in #289
  - [x] Real Time Global Illumination ([1](https://reddit.com/r/rust_gamedev/comments/ixocl2/real_time_diffuse_global_illumination_for_static/)) - ✔️ done by @miolad in #295
- [x] Library & Tooling Updates
  - [x] legion 0.3 ([1](https://reddit.com/r/rust/comments/io6evk/legion_v03_released_and_now_part_of_the_amethyst)) - ✔️ done by @ozkriff in #312
  - [x] thunderdome ([1](https://github.com/LPGhatguy/thunderdome)) - ✔️ done by @LPGhatguy in #283
  - [x] fontdue ([1](https://reddit.com/r/rust/comments/ilnd41/fontdue_the_fastest_font_renderer_in_the_world/)) - ✔️ done by @ozkriff in #312
  - [x] ultraviolet v0.6 ([1](https://reddit.com/r/rust/comments/ir24mp/announcing_ultraviolet_06_including_support_for)) - ✔️ done by @ozkriff in #312
  - [x] Mun - ✔️ done by @Wodann in #292
  - [x] audir ([1](ttps://github.com/norse-rs/audir)) - ✔️ done by @msiglreith in #286
  - [x] crevice ([1](https://github.com/LPGhatguy/crevice), [2](https://twitter.com/LPGhatguy/status/1308499131212599296)) - ✔️ done by @LPGhatguy in #283
  - [x] femtovg ([1](https://github.com/femtovg/femtovg), [2](https://reddit.com/r/rust_gamedev/comments/j1fx9u/femtovg_canvas2d_rendering_api_in_rust_based_on)) - ✔️ done by @adamnemecek in #287
  - [x] gfx ([1](https://reddit.com/r/rust/comments/ic9e62/release_announcement_for_gfxhal06_and_wgpu06/), [2](https://reddit.com/r/rust_gamedev/comments/i8np5v/simplified_instancing_tutorial_learn_wgpu), [3](https://reddit.com/r/rust_gamedev/comments/ixocl2/real_time_diffuse_global_illumination_for_static)) - ✔️ done by @kvark in #279
  - [x] Riddle ([1](https://github.com/vickles/riddle), [2](https://reddit.com/r/rust_gamedev/comments/j0xa3s/riddle_010_a_rust_native_sdllike_library)) - ✔️ done by @vickles in #284
  - [x] miniquad/macroquad ([1](https://twitter.com/fedor_games/), [2](https://twitter.com/kakoeimon/status/1311171685773701120)) - ✔️ done by @not-fl3 in #310
  - [x] bracket-lib - ✔️ done by @thebracket in #303
  - [x] tetra 0.5 ([1](https://twitter.com/17cupsofcoffee/status/1301210538299609088), [2](https://twitter.com/fischspiele/status/1301269497370873867)) - ✔️ done by @17cupsofcoffee in #293
  - [x] Bevy ([1](https://bevyengine.org/news/bevy-0-2/), [2](https://reddit.com/r/rust/comments/iw1yyp/bevy_02/)) - ✔️ done by @cart in #297
  - [x] rg3d - ✔️ done by @mrDIMAS in #288
  - [x] godot-rust v0.9 ([1](https://twitter.com/Extrawurst/status/1307797031210147840)) - ✔️ done by @ozkriff in #312

Final steps:

- [x] final review - ✔️ done by everyone
- [x] publish - ✔️ done @ozkriff
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev - ✔️ done @ozkriff
- [x] add comment links - ✔️ done @ozkriff
- [x] add a draft of the 15 newsletter - ✔️ done by @ozkriff in #314

**Comment by ozkriff** [comment]
📜 Updated the structure/list of sections!

**Comment by krupitskas** [comment]
I'd like to take An OpenGL preprocessor for Rust (1)

**Comment by adamnemecek** [comment]
I'll take femtovg.

**Comment by Terkwood** [comment]
I will submit an update about BUGOUT. ⚫⚪🐛

Thank you.

**Comment by LPGhatguy** [comment]
I can submit updates about my tagged libraries here!

**Comment by troligtvis** [comment]
I will add my progress of my game in the Bevy section :)

**Comment by miolad** [comment]
Hi, i'm the author of [this](https://www.reddit.com/r/rust_gamedev/comments/ixocl2/real_time_diffuse_global_illumination_for_static/) demo, and I've been proposed to add an entry in the newsletter about it, count me in!

**Comment by roalyr** [comment]
I will write about pGLOWrpg.

**Comment by vickles** [comment]
I'll write about riddle

**Comment by cdsupina** [comment]
@tigleym and I would like to write a game update section on the progress made on space_shooter_rs.

**Comment by hugopeixoto** [comment]
I'll write the update for "Rust, gamedev, ECS, and bevy"

**Comment by thebracket** [comment]
I'd be willing to contribute an update for Nox Futura, a small update for bracket-lib, and ideally sneak in a mention of the book I'm about to release (I should be NDA free by the time this is due, if not it'll have to wait a month).

**Comment by andii1701** [comment]
I'll write up my own game, Tetris Bane

**Comment by ozkriff** [comment]
Ping @AngelOnFira @not-fl3 @thebracket @termhn  - how're your sections going? :)

**Comment by ozkriff** [comment]
Btw, are there any volunteers to take some of the sections that are still free?

**Comment by AngelOnFira** [comment]
@ozkriff I have a decent amount of time today, most of them look like they're free with someone that might do it. Can you assign, say 3, to me?

**Comment by thebracket** [comment]
My plan is to get something put together today. I presented at the
Roguelike Celebration this weekend, so that ate *all* my time.

**Comment by ozkriff** [comment]
Grabbing "Garden", "galangua", "Threading WGPU Resource Loading with Rayon", and "So you want to live-reload Rust".

**Comment by ozkriff** [comment]
Also taking "legion", "fontdue", "ultraviolet", "rust-wasm-hotreload", and "godot-rust".

**Comment by ozkriff** [comment]
The final PR: #313 (_"Newsletter 14"_) - everyone is invited to review!

**Comment by ozkriff** [comment]
https://rust-gamedev.github.io/posts/newsletter-014 :tada: 

As always, huge thanks to all contributors and reviewers! :crab::crab:

**Comment by ozkriff** [comment]
Next coordination issue: #320 ("Newsletter 15")
