### ISSUE TITLE
Newsletter 15

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#320]
Feel free to suggest sections!

If you want to help writing the newsletter:

- Read **[CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md)**.
- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just an invitation to write the corresponding section if you want, but anyone is free to take it.
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint, please.
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #75)
  - Mention this issue in your PR's description to link it all together.

The soft deadline for all section PRs is 2020.11.04.

Current structure/status (I'll try to keep this updated):

- [x] Game Updates
  - [x] Veloren ([1](https://veloren.net/)) - ✔️ done by @AngelOnFira in #341
  - [x] Crate Before Attack ([1](https://twitter.com/CrateAttack)) - ✔️ done by @koalefant in #350
  - [x] Egregoria ([1](http://douady.paris/blog/egregoria_6.html)) - ✔️ done by @Uriopass in #328
  - [x] A/B Street ([1](https://twitter.com/CarlinoDustin/status/1314805932635815936)) - ✔️ done by @dabreegster in #336
  - [x] Worship The Sun ([1](https://tuzz.tech/blog/taking-the-plunge), [2](https://reddit.com/r/rust_gamedev/comments/j3trsk/gamedev_notes_1_taking_the_plunge)) - ✔️ done by @tuzz in #325
  - [x] Garden ([1](https://cyberplant.xyz/)) - ✔️ done by @logicsoup in #355
  - [x] Akigi ([1](https://devjournal.akigi.com)) - ✔️ done by @AngelOnFira in #342
  - [x] Sun Prison ([1](https://github.com/ropewalker/sun_prison), 2) - ✔️ done by @ropewalker in #344
  - [x] Camp Misty ([1](https://github.com/ReeCocho/camp-misty), [2](https://reddit.com/r/rust/comments/j8wqfi/new_to_rust_and_decided_to_make_a_game)) - ✔️ done by @ReeCocho in #323
  - [x] Antorum ([1](https://ratwizard.dev/dev-log/antorum/21), [2](https://ratwizard.dev/dev-log/antorum/22)) - ✔️ done by @Dooskington in #321
  - [x] Honor Sagas ([1](https://khonsulabs.itch.io/honorsagas/devlog/192252/the-honor-sagas-devtober-postmortem)) - ✔️ done by @ecton in #349
  - [x] YAWC - ✔️ done by @junkmail22 in #346
  - [x] Power Kick ([1](https://kakoeimon.itch.io/power-kick), [2](https://twitter.com/kakoeimon)) - ✔️ done by @kakoeimon in #327
  - [x] rymd ([1](https://profan.itch.io/rymd)) - ✔️ done by @profan in #353
  - [x] pGLOWrpg ([1](https://twitter.com/pglowrpg)) - ✔️ done by @roalyr in #315
  - [x] Space Shooter - ✔️ done by @tigleym & @cdsupina in #337
  - [x] Weegames ([1](https://yeahross.itch.io/weegames), [2](https://youtu.be/sstqGppo7L4))- ✔️ done by @yeahross0 in #338
  - [x] Canon Collision ([1](https://canoncollision.com)) - ✔️ done by @rukai in #337
  - [x] galaxy-sim.github.io ([1](https://github.com/Katsutoshii/barnes-hut-rs), [2](https://twitter.com/zephybite/status/1311384855276470272)) - ✔️ done by @ozkriff in #359
  - [x] LudumDare 47 ([1](https://blog.kuviman.com/2020/10/18/ludumdare47.html), [2](https://ldjam.com/events/ludum-dare/47/time-ghosts), [3](https://ldjam.com/events/ludum-dare/47/quantum-loops), ...) - ✔️ done by @ozkriff in #359
- [x] Learning Material Updates
  - [x] nyxtom's articles ([1](https://nyxtom.dev/2020/10/06/ecs-in-rust), [2](https://nyxtom.dev/2020/10/07/winit-rust), [3](https://nyxtom.dev/2020/10/08/framebuffers/)) - ✔️ done by @nyxtom in #329
  - [x] Creating a Snake Clone in Rust, with Bevy ([1](https://mbuffett.com/posts/bevy-snake-tutorial/), [2](https://reddit.com/r/rust/comments/jcv4ck/making_a_snake_clone_with_bevy)) - ✔️ done by @marcusbuffett in #330
  - [x] Rust FFI: Microsoft Flight Simulator SDK ([1](https://youtube.com/watch?v=jNNz4h3iIlw), [2](https://youtube.com/watch?v=ugiR9M16fwg), [3](https://reddit.com/r/rust/comments/j92jc0/rust_ffi_microsoft_flight_simulator_sdk_part_1)) - ✔️ done by @ozkriff in #359
  - [x] How to: Rust + SDL2 + OpenGL on the web ([1](https://blog.therocode.net/2020/10/a-guide-to-rust-sdl2-emscripten)) - ✔️ done by @therocode in #326
- [x] Library & Tooling Updates
  - [x] rust-psp - ✔️ done by @sajattack in #331
  - [x] gbemu ([1](https://github.com/BlueBlazin/gbemu), [2](https://reddit.com/r/rust/comments/j8vw84/i_made_a_gameboygameboy_color_emulator)) - ✔️ done by @ozkriff in #360
  - [x] skyline-rs ([1](https://jam1.re/blog/rust-for-game-modding)) - ✔️ done by @jam1garner in #352
  - [x] shared-arena ([1](https://github.com/sebastiencs/shared-arena), [2](https://reddit.com/r/rust/comments/jddens/announcing_shared_arena_a_threadsafe_memory_pool)) - ✔️ done by @ozkriff in #360
  - [x] glam - ✔️ done by @bitshifter in #332
  - [x] density-mesh ([1](https://github.com/PsichiX/density-mesh), [2](https://reddit.com/r/rust/comments/j73ijj/densitymesh_image_to_2d_mesh_converter), [3](https://reddit.com/r/rust_gamedev/comments/j7oylx/densitymesh_v12)) - ✔️ done by @ozkriff in #360
  - [x] rapier ([1](https://www.dimforge.com/blog/2020/10/01/this-month-in-dimforge/), [2](https://twitter.com/dimforge/status/1321138642778206211)) - ✔️ done by @sebcrozet in #354
  - [x] physme ([1](https://crates.io/crates/physme), [2](https://twitter.com/the_walterpi/status/1314847530316894208)) - ✔️ done by @walterpie in #356
  - [x] Mun - ✔️ done by @Wodann in #319
  - [x] building-blocks ([1](https://github.com/bonsairobo/building-blocks), [2](https://github.com/bonsairobo/building-blocks/releases/tag/v0.1.0), [3](https://reddit.com/r/rust_gamedev/comments/jim8ih/introducing_buildingblocks_v010_a_voxel_library)) -  ✔️ done by @bonsairobo in #358
  - [x] rust-gpu v0.1 ([1](https://github.com/EmbarkStudios/rust-gpu), [2](https://github.com/EmbarkStudios/rust-gpu/releases/tag/v0.1), [3](https://reddit.com/r/rust/comments/jg056t/introducing_rustgpu_v01), [4](https://news.ycombinator.com/item?id=24858172), [5](https://reddit.com/r/rust/comments/jg08jb/the_future_of_rlsl), [6](https://twitter.com/repi/status/1319274584915365888)) - ✔️ done by @AngelOnFira in #351
  - [x] gfx - ✔️ done by @kvark in #322
  - [x] ggez - ✔️ done by @icefoxen in #345
  - [x] miniquad/macroquad ([1](https://twitter.com/fedor_games/)) - ✔️ done by @not-fl3 in #348
  - [x] rg3d & hrtf ([1](https://twitter.com/DmitryS36934349)) - ✔️ done by @mrDIMAS in #339
  - [x] Bevy - ✔️ done by @cart in #347
  - [x] tetra & ogmo3 ([1](https://twitter.com/17cupsofcoffee)) - ✔️ done by @17cupsofcoffee in #333
  - [x] Wilds ([1](https://github.com/zakarumych/wilds)) - ✔️ done by @zakarumych in in #340
  - [x] fastnbt & fastanvil ([1](https://github.com/owengage/fastnbt), [2](https://reddit.com/r/rust/comments/jj6k9b/any_minecraft_fans)) - ✔️ done by @ozkriff in #360
  - [x] mcproto ([1](https://reddit.com/r/rust/comments/jcbawo/the_entire_minecraft_protocol_in_rust)) - ✔️ done by @ozkriff in #360
  - [x] Ajour ([1](https://github.com/casperstorm/ajour), [2](https://reddit.com/r/rust/comments/j63h4b/ajour)) - ✔️ done by @casperstorm in #324
  - [x] Valve's Proton 5.13 / media-converter ([1](https://reddit.com/r/rust/comments/jbzorm/valves_proton_513_now_uses_rust)) - ✔️ done by @PatrickHoward in #335

Final steps:

- [x] final review - ✔️ done by everyone
- [x] publish - ✔️ done by @ozkriff
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev - ✔️ done by @ozkriff
- [x] add comment links - ✔️ done by @ozkriff
- [x] add a draft of the 16 newsletter - ✔️ done by @ozkriff in #364

**Comment by walterpie** [comment]
Hey, as the creator of physme I'd love to write a short overview of what it's for and what it's not for and why I made it.

**Comment by casperstorm** [comment]
I'll happily write about Ajour. I'll get it done by tomorrow.

**Comment by Dooskington** [comment]
Will write about the October updates for my project Antorum Online.

**Comment by cdsupina** [comment]
@tigleym and I will write an update on space_shooter_rs.

**Comment by ecton** [comment]
I'd love to write about my game, The Honor Sagas. Thank you again for the invite.

**Comment by sajattack** [comment]
Can we add a section for a rust-psp update? I got tetris running with it :smile:

**Comment by ReeCocho** [comment]
I'd like to write a bit about my game Camp Misty. Thank you for the invite!

**Comment by roalyr** [comment]
Game updates, pGLOWrpg #315

**Comment by bitshifter** [comment]
A made a new release of `glam` a couple of days ago with of few new features of note, I'd like to add a short note about that if possible :)

**Comment by tuzz** [comment]
I'm happy to write a quick introduction for my puzzle-platform game.

**Comment by therocode** [comment]
I'll add my rust+SDL2+opengl+emscripten, cheers for the ping 👍

**Comment by junkmail22** [comment]
Hi, I'm here again and I'm planning to write another update for Project YAWC which actually includes contact info and links to pages.

**Comment by PatrickHoward** [comment]
I'll take on a section on Proton!

**Comment by AngelOnFira** [comment]
@ozkriff Akigi isn't on there under the game section, but I'll take it :smiley:

**Comment by logicsoup** [comment]
Hi, I’d like to write the Garden update.

**Comment by icefoxen** [comment]
I'd like to make an update for ggez, since I'm trying to get a new release done before the end of the year and want to drum up interest/contributions.  However, I'm also not sure whether this is too early, since I don't have a whole lot actually done for the update yet.  Anyone have thoughts or opinions?

**Comment by ozkriff** [comment]
Taking "galaxy-sim.github.io", "LudumDare 47", and "Rust FFI: Microsoft Flight Simulator SDK".

**Comment by AngelOnFira** [comment]
I'll take Rust GPU as it looks as it hasn't been picked up yet

**Comment by jam1garner** [comment]
I can do "Rust for Modding Smash Ultimate"

**Comment by profan** [comment]
I'd like to nab a section for a game I'm working on being made with macroquad called "rymd", thanks! (@not-fl3 sent me here, hi)

**Comment by bonsairobo** [comment]
I'll take the building-blocks section.

**Comment by sebcrozet** [comment]
If it is not too late, I took the `Dimforge` section. Though to make the section more precise, I added a `Rapier` section instead of `Dimforge`. I hope this is OK.

**Comment by ozkriff** [comment]
Ping @walterpie @bonsairobo @Twister915 - how're your sections going? :)

**Comment by walterpie** [comment]
Sorry for the quietness. I work all week and have no time for anything. I'll have it finished by today, in at most 7 hours

**Comment by bonsairobo** [comment]
@ozkriff Sorry about the delay. Working on it now, should be done today. I just have to cut another release for building-blocks, write a quick release post, then I'll bundle it into the newsletter.

**Comment by ozkriff** [comment]
@walterpie @bonsairobo no worries, I'm struggling to find time for the newsletter myself :) Hope to finish it today though.

**Comment by ozkriff** [comment]
Taking "shared-arena", "gbemu",  and "fastnbt & fastanvil".

**Comment by ozkriff** [comment]
Taking "density-mesh" and "mcproto".

**Comment by ozkriff** [comment]
The final PR: #361 (_"N15: Release"_) - everyone is invited to review!

**Comment by ozkriff** [comment]
https://rust-gamedev.github.io/posts/newsletter-015 :tada: 

As always, huge thanks to all contributors and reviewers! :crab::crab::crab:
