### ISSUE TITLE
Newsletter 16

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#365]
Feel free to suggest sections!

If you want to help writing the newsletter:

- Read **[CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md)**.
- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just an invitation to write the corresponding section if you want, but anyone is free to take it.
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint, please.
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

The soft deadline for all section PRs is 2020.12.03.

Current structure/status (I'll try to keep this updated):

- [x] Rust GameDev Podcast 3 ([1](https://rustgamedev.com/episodes/interview-with-chris-parsons), [2](https://reddit.com/r/rust_gamedev/comments/jwm513/rust_game_dev_podcast_episode_3) - ✔️ done by @patchfx in #396
- [x] Survey Reminder ([1](https://reddit.com/r/rust/comments/joj5e0/rust_gamedev_ecosystem_survey), [2](https://reddit.com/r/rust_gamedev/comments/jojn8s/rust_gamedev_ecosystem_survey)) - ✔️ done by @erlend-sh in #374
- [x] Game Updates
  - [x] A/B Street ([1](https://twitter.com/CarlinoDustin), [2](https://reddit.com/r/abstreet)) - ✔️ done by @dabreegster in #369
  - [x] Veloren 0.8 ([1](https://veloren.net/)) - ✔️ done by @AngelOnFira in #393
  - [x] fbsim ([1](https://iantayler.com/2020/11/22/fbsim-football-playing-ai-agents-in-rust/), [2](https://reddit.com/r/rust_gamedev/comments/jz4x1f/fbsim_footballplaying_ai_agents_in_rust_with/)) - ✔️ done by @IanTayler in #377
  - [x] Akigi ([1](https://devjournal.akigi.com)) - ✔️ done by @AngelOnFira in #395
  - [x] Antorum ([1](https://ratwizard.dev/dev-log/antorum)) - ✔️ done by @Dooskington in #384
  - [x] rymd ([1](https://twitter.com/_profan)) - ✔️ done by @profan in #387
  - [x] shotcaller v0.3.1 ([1](https://github.com/amethyst/shotcaller), [2](https://twitter.com/AmethystEngine/status/1331994516761550850)) - ✔️ done by @erlend-sh in #375
  - [x] space_shooter_rs - ✔️ done by @cdsupina in #388
  - [x] gameoff2020 ([1](https://reddit.com/r/rust_gamedev/comments/k3ozd4/spaceshooter_gameoff2020_made_with_luminance_hecs), [2](https://itch.io/jam/game-off-2020/rate/837014), TODO: more?) - ✔️ done by @mockersf, @grzi & @ozkriff in #390, #402, #403
- [x] Learning Material Updates
  - [x] Hands-On Rust ([1](https://pragprog.com/titles/hwrust/hands-on-rust/), [2](https://reddit.com/r/rust_gamedev/comments/jsyz5d/handson_rust_new_book_in_beta_teaching_rust), [3](https://twitter.com/herberticus/status/1326581976778878976)) - ✔️ done by @thebracket in #389
  - [x] Why Rust is the Future of Game Development ([1](https://thefuntastic.com/blog/why-rust-is-the-future-game-dev), [2](https://reddit.com/r/rust/comments/jqux1s/why_rust_is_the_future_of_game_development)) - ✔️ done by @ozkriff in #403
  - [x] ECS scheduler thoughts, pt1 ([1](https://ratysz.github.io/article/scheduling-1/), [2](https://reddit.com/r/rust_gamedev/comments/jujaul/ecs_scheduler_thoughts_part_1)) - ✔️ done by @ratysz in #380
  - [x] How to build a multiplayer game ([1](https://youtube.com/watch?v=Yb-QR3Vm3sk), [2](https://estada.ch/2020/11/2/how-to-build-a-multiplayer-game-rustfest-global-2020-pre-event/), [3](https://twitter.com/dns2utf8/status/1323592218020642817)) - ✔️ done by @ozkriff in #403
  - [x] Chess game in Rust using Bevy ([1](https://caballerocoll.com/blog/bevy-chess-tutorial/)) - ✔️ done by @guimcaballero in #372
  - [x] Learn Wgpu ([1](https://sotrh.github.io/learn-wgpu/news/#november-2020-cleanup-content-freeze-and-patreon)) - ✔️ done by @sotrh #370
- [x] Library & Tooling Updates
  - [x] cargo-mobile ([1](https://dev.brainiumstudios.com/2020/11/24/cargo-mobile.html)) - ✔️ done by @francesca64 in #392
  - [x] profiling ([1](https://crates.io/crates/profiling), [2](https://twitter.com/aclysma/status/1332001529708986373)) - ✔️ done by @aclysma in #371
  - [x] rkyv ([1](https://github.com/djkoloski/rkyv), [2](https://reddit.com/r/rust/comments/jss6h4/rkyv_a_zerocopy_deserialization_framework)) - ✔️ done by @djkoloski in #368
  - [x] assets_manager - ✔️ done by @a1phyr in #391
  - [x] Terramach ([1](https://github.com/lykhonis/terramach), [2](https://reddit.com/r/rust_gamedev/comments/jm5b2m/terramach_gui_framework_built_with_skia_in_rust)) - ✔️ done by @AngelOnFira in #397
  - [x] glam - ✔️ done by @bitshifter in #399
  - [x] winit - ✔️ done by @francesca64 in #401
  - [x] Fluffl ([1](https://github.com/K-C-DaCosta/fluffl), [2](https://reddit.com/r/rust_gamedev/comments/jthdoq/fluffl_a_multimedia_layer_for_rust)) - ✔️ done by @ozkriff in #404
  - [x] rapier & salsa ([1](https://twitter.com/dimforge)) - ✔️ done by @sebcrozet in #400
  - [x] rib ([1](https://github.com/bmatthieu3/rib), [2](https://reddit.com/r/rust_gamedev/comments/jztr1g/rib_a_very_new_rust_collada_importer_for_your_3d)) - ✔️ done by @bmatthieu3 in #382
  - [x] kira ([1](https://crates.io/crates/kira), [2](https://crates.io/crates/kira)) - ✔️ done by @tesselode in #378
  - [x] gfx/wgpu ([1](https://reddit.com/r/rust/comments/jvfgog/the_big_picture_of_gfxwgpu_ecosystem/)) - ✔️ done by @kvark in #366
  - [x] iced 0.2 ([1](https://github.com/hecrj/iced/pull/637), [2](https://reddit.com/r/rust/comments/k1hkxq/iced_a_crossplatform_gui_library_new_release)) - ✔️ done by @hecrj in #398
  - [x] KAS 0.6 ([1](https://reddit.com/r/rust/comments/k1jejo/kas_gui_v06_release)) - ✔️ done by @dhardy in #376
  - [x] egui 0.4 ([1](https://twitter.com/ernerfeldt/status/1332670839796486144)) - ✔️ done by @ozkriff in #404
  - [x] Another World Suite ([1](https://github.com/malandrin/another-world-suite), [2](https://twitter.com/c_botana/status/1327593089989554178)) - ✔️ done by @ozkriff in #404
  - [x] Old Gods ([1](https://github.com/schell/old-gods), [2](https://reddit.com/r/rust/comments/k25hh8/the_old_gods_game_engine)) - ✔️ done by @ozkriff in #404
  - [x] macroquad - ✔️ done by @not-fl3 in #394
  - [x] dotrix ([1](https://github.com/lowenware/dotrix), [2](https://reddit.com/r/rust_gamedev/comments/jzgwgp/dotrix_3d_engine_weekly_update_1/), [3](https://reddit.com/r/rust_gamedev/comments/k3ri5d/dotrix_weekly_3)) - ✔️ done by @Lowentwickler in #386
  - [x] tetra & ogmo3 ([1](https://twitter.com/17cupsofcoffee)) - ✔️ done by @17cupsofcoffee in #367
  - [x] ggez - ✔️ done by @icefoxen in #385
  - [x] rg3d ([1](https://twitter.com/DmitryS36934349)) - ✔️ done by @mrDIMAS in #383
  - [x] F1 Telemetry TUI ([1](https://github.com/aldidana/f1-telemetry-tui), 2) - ✔️ done by @aldidana in #379
  - [x] bevmnist ([1](https://github.com/vleue/bevmnist), [2](https://twitter.com/FrancoisMockers/status/1330082228517400587)) - ✔️ done by @mockersf in #381

Final steps:

- [x] final review - ✔️ done by everyone
- [x] publish - ✔️ done by @ozkriff
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev - ✔️ done by @ozkriff
- [x] add comment links - ✔️ done by @ozkriff
- [ ] add a draft of the 17 newsletter - by @ozkriff

**Comment by Ratysz** [comment]
Taking "ECS scheduler thoughts, pt1"

**Comment by Dooskington** [comment]
I’ll do the Antorum update section.

**Comment by icefoxen** [comment]
I should do another ggez update!

**Comment by Lowentwickler** [comment]
I'll take dotrix

**Comment by djkoloski** [comment]
I'd like to write about rkyv.

**Comment by aclysma** [comment]
I can write something for profiling

**Comment by patchfx** [comment]
I'll pick up the podcast

**Comment by sotrh** [comment]
I'll take "Learn Wgpu News (1)"

**Comment by guimcaballero** [comment]
I'll take "Chess game in Rust using Bevy"

**Comment by bmatthieu3** [comment]
i will write something about rib

**Comment by profan** [comment]
I'll do rymd 👍

**Comment by hecrj** [comment]
I can write the `iced` update.

**Comment by IanTayler** [comment]
I'll take FBSim

**Comment by tesselode** [comment]
i'll take kira!

**Comment by bitshifter** [comment]
I will add a `glam` update.

**Comment by aldidana** [comment]
#379

**Comment by aldidana** [comment]
I added `F1 Telemetry TUI`

**Comment by mockersf** [comment]
I'll take bevmnist

**Comment by cedric-h** [comment]
![image](https://user-images.githubusercontent.com/25539554/100902267-b9ae2780-3492-11eb-957e-3f81667e03cf.png)
I would like to write a little something about my work in progress RPG made in Rust.

**Comment by cdsupina** [comment]
@tigleym and I will write about space_shooter_rs

**Comment by dns2utf8** [comment]
I did write a follow up to my talk "How to  build a multiplayer game":
https://estada.ch/2020/11/2/how-to-build-a-multiplayer-game-rustfest-global-2020-pre-event/

Is that what you had in mind?

**Comment by Ratysz** [comment]
I think [`cargo-mobile`](https://dev.brainiumstudios.com/2020/11/24/cargo-mobile.html) announcement should be in the newsletter. @francesca64?

**Comment by thebracket** [comment]
I'll get you something for *Hands-On Rust* today.

**Comment by ozkriff** [comment]
@dns2utf8 kinda, though newsletter sections are usually more like a short overview (in a few sentences) of the links themselves.

**Comment by francesca64** [comment]
@Ratysz thanks! I'll make a PR.

**Comment by francesca64** [comment]
Also, winit needs a new web maintainer (rust-windowing/winit#1777). Is this something the newsletter could signal boost?

**Comment by aclysma** [comment]
> Also, winit needs a new web maintainer ([rust-windowing/winit#1777](https://github.com/rust-windowing/winit/issues/1777)). Is this something the newsletter could signal boost?

Sounds like a good idea to me. I think the imgui crate is in a similar situation.

**Comment by ozkriff** [comment]
> Also, winit needs a new web maintainer ([rust-windowing/winit#1777](https://github.com/rust-windowing/winit/issues/1777)). Is this something the newsletter could signal boost?

Sure, feel free to add a section about it!

**Comment by ozkriff** [comment]
Ping @cedric-h @bitshifter @hecrj, how're your sections going? :) Hope to finish the final draft today.

**Comment by hecrj** [comment]
@ozkriff I should be able to open a PR in the next couple of hours.

**Comment by AngelOnFira** [comment]
@ozkriff I'm going to take some sections that still seem open: Akigi, Terramach, and Fluff for now.

**Comment by sebcrozet** [comment]
I'm going to take dimforge/rapier. Doing it right now.

**Comment by ozkriff** [comment]
Taking "Why Rust is the Future of GameDev", "How to build a multiplayer game", "egui", "Another World Suite", and "Old Gods",

**Comment by grzi** [comment]
Hello, I'll take GameOff 2 and add GameOff 3 also (A third game in rust submitted for Gameoff)

**Comment by ozkriff** [comment]
The final PR: #404 (_"N16: Release"_) - everyone is invited to review!

**Comment by ozkriff** [comment]
:tada: https://rust-gamedev.github.io/posts/newsletter-016 :tada: 

Huge thanks to all contributors and reviewers! :crab::crab::crab:

**Comment by kvark** [comment]
You made it! Thank you for all the hard work @ozkriff !

**Comment by emilk** [comment]
> Taking "Why Rust is the Future of GameDev", "How to build a multiplayer game", "fluffl", "egui", "Another World Suite", and "Old Gods",

Thanks for taking on Egui - I was a bit too busy this week to do it myself! ❤️
