### ISSUE TITLE
Newsletter 17

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#408]
Feel free to suggest sections!

If you want to help writing the newsletter:

- Read **[CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md)**.
- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just an invitation to write the corresponding section if you want, but anyone is free to take it.
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint, please.
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

The soft deadline for all section PRs is 2021.01.06

Current structure/status (I'll try to keep this updated):

- [x] Meetup - ✔️ done by @ozkriff in #450
- [x] Rust GameDev Podcast 4 ([1](https://rustgamedev.com/episodes/interview-with-fedor-logachev), [2](https://reddit.com/r/rust_gamedev/comments/kit4pa/rustgamedev_podcast_4_fedor_logachev)) - ✔️ done by @ozkriff in #450
- [x] Game Updates
  - [x] Way of Rhea - ✔️ done by @MasonRemaley in #407
  - [x] Veloren ([1](https://veloren.net/)) - ✔️ done by @AngelOnFira in #422
  - [x] A/B Street & 15 Minute Santa ([1](https://twitter.com/CarlinoDustin), [2](https://reddit.com/r/abstreet), [3](https://reddit.com/r/rust_gamedev/comments/khkrdl/15minute_santa)) - ✔️ done by @dabreegster in #411
  - [x] Egregoria - ✔️ done by @Uriopass in #413
  - [x] doukutsu-rs ([1](https://reddit.com/r/rust/comments/kh79r1/made_my_rust_remake_of_cave_story_engine)) - ✔️ done by @alula in #432
  - [x] Antorum ([1](https://ratwizard.dev/dev-log/antorum/)) - ✔️ done by @Dooskington in #419
  - [x] Zombie Shooter - ✔️ done by @Aunmag in #445
  - [x] Akigi ([1](https://devjournal.akigi.com)) - ✔️ done by @chinedufn in #437
  - [x] Swoop ([1](https://reddit.com/r/rust_gamedev/comments/k72oqs/i_wanted_to_learn_webgl_so_i_made_a_small_game), [2](https://sdfgeoff.github.io/wasm_minigames/a_first_game_swoop.html)) - ✔️ done by @sdfgeoff in #429
  - [x] Harvest Hero - ✔️ done by @Bombfuse in #418
  - [x] FreeNukum ([1](https://gitlab.com/silwol/freenukum), [2](https://reddit.com/r/rust_gamedev/comments/k9dw50/freenukum_a_clone_of_the_1991_dos_game_duke_nukem/)) - ✔️ done by @silwol in #430
  - [x] OpenEtG JS->Rust story ([1](https://reddit.com/r/rust/comments/k3jy5g/i_rewrote_10k_lines_of_js_into_rust_over_the_last)) - ✔️ done by @AngelOnFira in #449
  - [x] Weegames - ✔️ done by @yeahross0 in #416
  - [x] Shotcaller - ✔️ done by @erlend-sh in #431
  - [x] Cheese ([1](https://expenses.itch.io/cheese), [2](https://reddit.com/r/rust_gamedev/comments/k4tyn8/ive_been_working_on_this_rts_game_for_the_2020/)) - ✔️ done by @expenses in #420
  - [x] vollmond ([1](https://puppetmaster.itch.io/vollmond), [2](https://twitter.com/fischspiele/status/1344780158641860611)) - ✔️ done by @puppetmaster- in #439
- [x] Learning Material Updates
  - [x] How to Revive a Dead Rust Project ([1](https://youtube.com/watch?v=qoCryIy4bFE), [2](https://twitter.com/carlosupina/status/1341763006716407808)) - ✔️ done by @tigleym in #412
  - [x] Build Pikachu game in Rust ([1](https://reddit.com/r/rust/comments/k8ppyp/build_the_pikachu_game_in_rust)) - ✔️ done by @danbugs in #417
  - [x] re-creating a retro screensaver ([1](https://www.youtube.com/watch?v=d9lsT4kJo44)) - ✔️ done by @septum in #427
  - [x] Rendering bezier strokes with SDFs ([1](https://vladjuckov.github.io/beziers-sdf/), [2](https://twitter.com/VladZhukov0/status/1338545036405796865)) - ✔️ done by @pum-purum-pum-pum in #435
  - [x] Nannou: creative coding with Rust ([1](https://youtu.be/Ml6tpyTyXhM)) - ✔️ done by @septum in #421
  - [x] Triangle From Scratch ([1](https://rust-tutorials.github.io/triangle-from-scratch), [2](https://github.com/rust-tutorials/triangle-from-scratch), [3](https://twitter.com/Lokathor/status/1342720757806190592)) - ✔️ done by @Lokathor  in #450
  - [x] Undergrad Thesis on game scripting for Legion ([1](https://twitter.com/sayadiguin/status/1342198284849455106), [2](https://community.amethyst.rs/t/undergrad-thesis-on-game-scripting-for-legion/1753)) - ✔️ done by @pablodiegoss in #425
  - [x] WASM Games from Scratch - ✔️ done by @sdfgeoff in #429
- [x] Library & Tooling Updates
  - [x] thermite ([1](https://github.com/raygon-renderer/thermite), [2](https://reddit.com/r/rust/comments/k9i580/thermite_simd_melt_your_cpu_early_announcement/)) - ✔️ done by @AngelOnFira in #442
  - [x] Mun - ✔️ done by @Wodann in #433
  - [x] kira 0.2 & 0.3 ([1](https://reddit.com/r/rust/comments/k87kwj/kira_game_audio_library_v020), [2](https://reddit.com/r/rust/comments/kkf1jz/kira_game_audio_library_v030), [3](https://twitter.com/tesselode/status/1342878087990685700)) - ✔️ done by @tesselode in #428
  - [x] polyhedron-ops - ✔️ done by @AngelOnFira in #448
  - [x] raw-gl-context ([1](https://github.com/glowcoil/raw-gl-context)) - ✔️ done by @glowcoil in #438
  - [x] SPIR-Q 0.4.10 ([1](https://reddit.com/r/rust_gamedev/comments/kgv4gh/spirq_0410_customized_shader_reflection_no_hassle/)) - ✔️ done by @PENGUINLIONG in #434
  - [x] rust-gpu v0.2 (+SHADERed) ([1](https://reddit.com/r/rust/comments/k6o7dt/announcing_rustgpu_v02)) - ✔️ done by @XAMPPRocky in #426
  - [x] egui 0.5 & 0.6 ([1](https://twitter.com/ernerfeldt/status/1338224408071196674), [2](https://twitter.com/ernerfeldt/status/1342956640023289861)) - ✔️ done by @emilk in #415
  - [x] tetra ([1](https://twitter.com/17cupsofcoffee)) - ✔️ done by @17cupsofcoffee in #409
  - [x] ggez - ✔️ done by @icefoxen in #447
  - [x] macroquad ([1](twitter.com/fedor_games), [2](https://reddit.com/r/rust_gamedev/comments/kend22/made_a_bloody_calculator_with_rust_and_wasm)) - ✔️ done by not-fl3 in #424
  - [x] rg3d/rusty-editor ([1](https://twitter.com/DmitryNStepanov), [2](https://reddit.com/r/rust/comments/kad35c/i_made_a_level_in_rustyeditor_which_is_a_scene/), [3](https://old.reddit.com/r/rust/comments/k77u3q/rg3d_v016_featurerich_and_easytouse_game_engine/)) - ✔️ done by @mrDIMAS
  - [x] Starframe ([1](https://twitter.com/moletrooper/status/1338066680724008960)) - ✔️ done by @MoleTrooper in #414
  - [x] dotrix ([1](https://github.com/lowenware/dotrix), [2](https://reddit.com/r/rust_gamedev/comments/jzgwgp/dotrix_3d_engine_weekly_update_1/), [3](https://reddit.com/r/rust_gamedev/comments/k3ri5d/dotrix_weekly_3), [4](https://reddit.com/r/rust_gamedev/comments/kaz0zt/dotrix_weekly_4), [5](https://reddit.com/r/rust_gamedev/comments/kfo5v1/dotrix_weekly_5), [6](https://reddit.com/r/rust_gamedev/comments/kjwoql/dotrix_weekly6)) - ✔️ done by @Lowentwickler in #441
  - [x] Bevy v0.4 ([1](https://reddit.com/r/rust/comments/kge7zy/bevy_04)) - ✔️ done by @cart in #436
  - [x] rpt ([1](https://reddit.com/r/rust/comments/k81wwi/rpt_v01_a_physicallybased_path_tracer)) - ✔️ done by @ekzhang in #410 & #446
  - [x] Textyle ([1](https://reddit.com/r/rust_gamedev/comments/khl8jq/textyle_online_tilemap_editor_rust)) - ✔️ done by @AngelOnFira in #443
  - [x] playground.meteorlinker.com ([1](http://playground.meteorlinker.com), [2](https://reddit.com/r/rust/comments/kk6i38/write_mini_graphics_demos_in_rust_in_the_browser)) - ✔️ done by @AnthonyYoManz in #423

Final steps:

- [x] final review - by everyone
- [x] publish - by @ozkriff
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @ozkriff
- [x] add comment links - by @ozkriff
- [x] add a draft of the 18 newsletter - by @ozkriff

**Comment by PsichiX** [comment]
getting raui/oxygengine for tomorrow :D

**Comment by MoleTrooper** [comment]
I'll add a bit about the recent [starframe](https://github.com/moletrooper/starframe) [physics improvements](https://twitter.com/moletrooper/status/1338066680724008960) if it's cool :)

**Comment by Dooskington** [comment]
Will take care of the Antorum section some time tonight ⚔️

**Comment by ekzhang** [comment]
Thanks, I can add a short section about rpt. 🙂

**Comment by cart** [comment]
I'll take bevy!

**Comment by dabreegster** [comment]
I'll write up A/B Street & 15m Santa

**Comment by PENGUINLIONG** [comment]
Will take SPIR-Q!

**Comment by Lowentwickler** [comment]
I take dotrix!

**Comment by alula** [comment]
I take d-rs

**Comment by chinedufn** [comment]
I'll take Akigi

**Comment by XAMPPRocky** [comment]
I'll take rust-gpu 0.2

**Comment by serprex** [comment]
Fun thing about the openEtG Rust/JS rewrite is that the following month I rewrote the server from node.js into Rust

https://github.com/serprex/openEtG/commit/e26a92eab81dbb53f247a2a6040a7491e727ee62

Ended up adding 2k lines to project, so not as much a 1:1 rewrite

**Comment by expenses** [comment]
I'll have a go at writing a piece for cheese : )

**Comment by Uriopass** [comment]
I'll take Egregoria :cityscape:

**Comment by septum** [comment]
I'll take re-creating a retro screensaver and Nannou: creative coding with Rust

**Comment by danbugs** [comment]
I'd like to work on "Build the Pikachu game in Rust" section from the Learning Material Updates.

**Comment by pablodiegoss** [comment]
I'll take the game scripting for legion thesis :D

**Comment by puppetmaster-** [comment]
I´ll take **Vollmond** in "Game Updates" 😄

**Comment by silwol** [comment]
I'll take **FreeNukum** in "Game Updates".

**Comment by AnthonyYoManz** [comment]
I've gone ahead and filled out the playground.meteorlinker.com section. Thanks for featuring it :D

**Comment by AngelOnFira** [comment]
Oh wow, there doesn't seem to be much free stuff (20 contributors to this issue :open_mouth:). @ozkriff feel free to assign a few to me if they end up not being taken by their recommended authors.

**Comment by sdfgeoff** [comment]
I will take swoop

**Comment by tesselode** [comment]
made a pull request for kira

**Comment by glowcoil** [comment]
I'll take raw-gl-context

**Comment by ozkriff** [comment]
> Fun thing with openEtG Rust/JS rewrite is that last month I rewrote server from node.js into Rust: [serprex/openEtG@e26a92e](https://github.com/serprex/openEtG/commit/e26a92eab81dbb53f247a2a6040a7491e727ee62)
> 
> Ended up adding 2k lines to project, so not as much a 1:1 rewrite

@serprex sorry, could you clarify a bit: it's additional info you'd like to be added to the section, right? Would you like to write that section?

**Comment by ozkriff** [comment]
> Oh wow, there doesn't seem to be much free stuff (20 contributors to this issue open_mouth). @ozkriff feel free to assign a few to me if they end up not being taken by their recommended authors.

Awesome! Assigning "thermite" and "Textyle" to you than :)

**Comment by ozkriff** [comment]
Any volunteers for the last free sections: "OpenEtG JS->Rust story" and "polyhedron-ops"?

**Comment by Lokathor** [comment]
[Triangle From Scratch](https://rust-tutorials.github.io/triangle-from-scratch/) ([GitHub repo](https://github.com/rust-tutorials/triangle-from-scratch)) is a new tutorial series. So far there's just one article for opening a window using the Win32 API, but more subjects and on more platforms will be added over time. From the author:
> The point isn't that we specifically care about drawing the triangle. That's just a goal that's easy to grasp. The point is that we're doing it with no dependencies as a way to get ourselves to learn about low level OS interaction details as we go. That said, the "no crates" rule is for educational purposes only; please feel free to use crates in normal situations.

**Comment by ozkriff** [comment]
Sorry that my reviews take so long, I have a hard time with this newsletter issue for various personal reasons. :snail:

**Comment by AngelOnFira** [comment]
No worries! Editing a newsletter of this size is no small feat. We all appreciate the work you put into it every month, and don't hold you against when it's released :heart_decoration:

**Comment by ozkriff** [comment]
> Any volunteers for the last free sections: "OpenEtG JS->Rust story" and "polyhedron-ops"?

Well, taking them :)

**Comment by PsichiX** [comment]
i'm sorry for the delay with my part, lots of work was blocking me, but today i can finally sit down and write Oxygengine/RAUI section :)

**Comment by ozkriff** [comment]
Aaaan finally here's the final PR: #450 (_"N17: Release"_) - everyone is invited to review.

**Comment by ozkriff** [comment]
It's out!

https://rust-gamedev.github.io/posts/newsletter-017

**Comment by emilk** [comment]
Good job @ozkriff !
