### ISSUE TITLE
Newsletter 18

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#455]
Feel free to suggest sections!

If you want to help writing the newsletter:

- Read **[CONTRIBUTING.md](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/CONTRIBUTING.md)**.
- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just an invitation to write the corresponding section if you want, but anyone is free to take it.
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint, please.
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

The deadline for all section PRs is 2021.02.03.

------

⚠️ [It was decided to try a shorter and more limited section format](https://github.com/rust-gamedev/rust-gamedev.github.io/issues/454): ⚠️

- Only one image (<300kb) or GIF (<2.5mb) before the text. With an optional caption and a mandatory alt text.
- All the (rendered) text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).
- No bold/italic/etc formatting - only links and one plain list without nesting per section.
- Third-person perspective.
- 80 chars per MD line and no other markdownlint warnings on CI.
- Only the following simple templates are allowed:

  <details>
    <summary>See the templates</summary>

    For games/apps/libs:

    ```md
    # [Gamename]

    ![alt text](img)
    _optional image label_

    [Gamename] ([GitHub], [Discord], [Twitter]) by [@nickname]
    is ... {short project description in one sentence}.

    {An overview of the recent updates with links to more details}.

    _Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

    {md links block}
    ```

    For articles/videos/etc:

    ```md
    # [Articlename]

    ![alt text](img)
    _optional image label_

    [@nickname] published an [article] about ...
    {overview what the resource is about}.

    _Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

    {md links block}
    ```

  </details>

_`CONTRIBUTING.md` isn't updated for this yet_.

## Current Structure & Status

(_I'll try to keep this updated_)

- [x] Meetup ([1](https://reddit.com/r/rust_gamedev/comments/ksflbm/the_first_rust_gamedev_meetup_is_this_saturday), [2](https://reddit.com/r/rust_gamedev/comments/ku2xkn/the_recording_from_the_first_rust_gamedev_meetup)) - ✔️ done by @AngelOnFira in #490
- [x] Rust GameDev Podcast 5 ([1](https://reddit.com/r/rust_gamedev/comments/l4muln/rustgamedev_podcast_5_alex_ene_dwarf_world), [2](https://twitter.com/rustgamedev/status/1352586814578515968)) - ✔️ done by @patchfx in #461
- [x] Game Updates
  - [x] Fish Game ([1](https://twitter.com/erlend_sh/status/1349731093730115585), [2](https://reddit.com/r/rust/comments/kx3hbi/fish_game_a_multiplayer_game_made_with_macroquad), [3](https://twitter.com/fedor_games/status/1353184363823960066)) - ✔️ done by @not-fl3 in #478
  - [x] Station Iapetus ([1](https://twitter.com/DmitryNStepanov/status/1354169722795917313), [2](https://github.com/mrDIMAS/StationIapetus)) - ✔️ done by @mrDIMAS in #471
  - [x] teki ([1](https://github.com/o2sh/teki), [2](https://reddit.com/user/o2sh/posts/), [3](https://twitter.com/OssamaHjaji)) - ✔️ done by @o2sh in #456
  - [x] oicana ([1](https://twitter.com/nikl_me/status/1350492266863976451), [2](https://niklme.itch.io/oicana)) - ✔️ done by @NiklasEi in #475
  - [x] SeniorSKY - ✔️ done by @pmathia0 in #466
  - [x] Flesh - ✔️ done by @Im-Oab in #470
  - [x] Bounty Bros - ✔️ done by @zicklag in #473
  - [x] Stellary 2 - ✔️ done by @dezajno in #476
  - [x] A/B Street ([1](https://twitter.com/CarlinoDustin), [2](https://reddit.com/r/abstreet)) - ✔️ done by @dabreegster in #469
  - [x] dwarf.world ([1](https://twitter.com/_AlexEne_)) - ✔️ done by @AlexEne in #474
  - [x] Way of Rhea - ✔️ done by @MasonRemaley in #479
  - [x] Paddlers 0.2 ([1](https://www.jakobmeier.ch/blogging/Paddlers_5.html)) - ✔️ done by @jakmeier in #465
  - [x] Theta Wave - ✔️ done by @cdsupina in #480
  - [x] Harvest Hero - ✔️ done by @Bombfuse in #482
  - [x] Antorum ([1](https://ratwizard.dev/dev-log/antorum/)) - ✔️ done by @Dooskington in #458
  - [x] Shotcaller ([1](https://reddit.com/r/rust_gamedev/comments/kveih9/shotcaller_mobagame_v040), [2](https://reddit.com/r/rust_gamedev/comments/l4l7bw/shotcaller_wip_art_pass_for_v05)) - ✔️ done by @erlend-sh in #486
  - [x] Veloren ([1](https://veloren.net/)) - ✔️ done by @AngelOnFira in #489
  - [x] Zemeroth ([1](https://twitter.com/ozkriff/status/1346422661187035136)) - ✔️ done by @ozkriff in #493
- [x] Learning Material Updates
  - [x] Hands-on-Rust new chapters ([1](https://twitter.com/herberticus)) - ✔️ done by @ozkriff in #484
  - [x] Triangle from Scratch: Win and WASM ([1](https://rust-tutorials.github.io/triangle-from-scratch/loading_opengl/win32.html), [2](https://twitter.com/Lokathor/status/1349076830527975424), [3](https://twitter.com/Lokathor/status/1351343658461667331)) - ✔️ done by @ozkriff in #484
  - [x] Rust Executable's Icon in Windows ([1](https://www.anthropicstudios.com/2021/01/05/setting-a-rust-windows-exe-icon), [2](https://www.reddit.com/r/rust_gamedev/comments/kraink/setting_a_rust_executables_icon_in_windows/)) - ✔️ done by @ozkriff in #484
  - [x] Exploring WebSocket with Rust and Tide ([1](https://javierviola.com/post/exploring-websocket-with-rust-and-tide/)) - ✔️ done by @pepoviola in #481
- [x] Engine Updates
  - [x] ggez v0.6-rc0 ([1](https://www.reddit.com/r/rust_gamedev/comments/kzm3rl/ggez_060rc0_released/)) - ✔️ done by @icefoxen in #472
  - [x] Tetra ([1](https://twitter.com/17cupsofcoffee)) - ✔️ done by @17cupsofcoffee in #457
  - [x] Dotrix v0.7 ([1](https://www.reddit.com/r/rust_gamedev/comments/kprl5y/dotrix_weekly_7)) - ✔️ done by @Lowentwickler in #488
  - [x] rg3d & rusty-editor - ✔️ done by @mrDIMAS in #471
- [x] Library & Tooling Updates
  - [x] rkyv v0.3 ([1](https://reddit.com/r/rust/comments/kxfbyl/rkyv_03_unarchiving_and_perfect_hashing/)) - ✔️ done by @djkoloski in #459
  - [x] Mun - ✔️ done by @Wodann in #483
  - [x] gamelisp v0.2 ([1](https://reddit.com/r/rust/comments/kp77vw/version_02_of_gamelisp)) - ✔️ done by @ozkriff in #492
  - [x] ldtk-rs - ✔️ done by @zicklag in #464
  - [x] bevy_ldtk - ✔️ done by @zicklag in #462
  - [x] kira v0.4 ([1](https://reddit.com/r/rust/comments/l3ma3d/kira_game_audio_library_v040)) - ✔️ done by @tesselode in #463
  - [x] Dimforge ([1](https://reddit.com/r/rust/comments/koe8kf/physics_simulation_with_rapier_2021_roadmap), [2](https://reddit.com/r/rust/comments/l7xrmw/this_month_in_dimforge_4_jan_2021)) - ✔️ done by @AngelOnFira in #491
  - [x] gfx/wgpu - ✔️ done by @kvark in #468
  - [x] imgui-rs - ✔️ done by @sanbox-irl in #485
  - [x] egui ([1](https://twitter.com/ernerfeldt)) - ✔️ done by @emilk in #477
  - [x] bevy_egui - ✔️ done by @mvlabat in #487
  - [x] chess-engine ([1](https://github.com/adam-mcdaniel/chess-engine), [2](https://reddit.com/r/rust/comments/l65e86/a_nostd_chess_engine_that_has_implementations_for)) - ✔️ done by @ozkriff in #492
  - [x] dcli ([1](https://github.com/mikechambers/dcli), [2](https://twitter.com/mesh/status/1353032038606020611)) - ✔️ done by @ozkriff in #492
  - [x] tgjones's Shader Playground ([1](https://twitter.com/_tim_jones_/status/1351932879647850499), [2](http://shader-playground.timjones.io/)) - ✔️ done by @ozkriff in #492

Final steps:

- [x] final review - ✔️ done by everyone
- [x] publish - ✔️ done by @ozkriff
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev - ✔️ done by @ozkriff
- [x] add comment links - ✔️ done by @ozkriff
- [x] add a draft of the 19 newsletter - 🚧 WIP by @ozkriff

_Editors_: @ozkriff @17cupsofcoffee @AngelOnFira

**Comment by 17cupsofcoffee** [comment]
I'll pick up the Tetra section after work :+1:

**Comment by Lowentwickler** [comment]
Taking Dotrix 👍

**Comment by o2sh** [comment]
I'd be more than happy to take care of Teki.

**Comment by djkoloski** [comment]
I’ll write a bit about rkyv.

**Comment by Dooskington** [comment]
I'll take Antorum 💯

**Comment by icefoxen** [comment]
I'll take `ggez` :salt:

**Comment by NiklasEi** [comment]
I'll write something about Oicana :video_game:

**Comment by logicsoup** [comment]
I'll try to write something up on Garden during the week

**Comment by tesselode** [comment]
i'll take kira

**Comment by pmathia0** [comment]
I'll write a section about my project (SeniorSKY), per Twitter DM invitation

**Comment by dabreegster** [comment]
I'll take A/B Street

**Comment by AlexEne** [comment]
I'll do dwarf.world

**Comment by sanbox-irl** [comment]
Hey i'm going to add a section for imgui-rs

**Comment by icefoxen** [comment]
> The deadline for all section PRs is 2021.02.03.

We might want to add a specific time on that, just to make life easier for editors?  I seem to have a tendency for last-minute submissions and don't want people to tell themselves "this submission is kinda past the deadline but I should just work a bit more and get it in anyway".  Just having a firm cutoff makes life simpler.

**Comment by dezajno** [comment]
I'll write a section about "Stellary 2" (game update)

**Comment by cdsupina** [comment]
@tigleym and I will write about Theta Wave https://github.com/amethyst/theta-wave

**Comment by ozkriff** [comment]
> The deadline for all section PRs is 2021.02.03.

It's time to deal with sections that are still free!

Taking:

- Hands-on-Rust new chapters 
- Triangle from Scratch: Win and WASM
- Rust Executable's Icon in Windows

**Comment by ozkriff** [comment]
Any volunteers for the last unclaimed sections: "gamelisp", "Dimforge", "chess-engine", "dcli", and "Shader Playground"?

**Comment by ozkriff** [comment]
Taking "gamelisp", "chess-engine" and "dcli".

**Comment by ozkriff** [comment]
Ping @AngelOnFira @logicsoup @erlend-sh @Lowentwickler @sanbox-irl, how're your WIP sections going? :)

**Comment by sanbox-irl** [comment]
Writing it up as we speak! Well, type

**Comment by ozkriff** [comment]
Also taking "Dimforge" & "Shader Playground".

Hope to have a final draft tomorrow morning and release the newsletter somewhere around 15:00 UTC.

**Comment by ozkriff** [comment]
Final PR - https://github.com/rust-gamedev/rust-gamedev.github.io/pull/494 - everyone is invited to review :)

**Comment by ozkriff** [comment]
:tada: https://rust-gamedev.github.io/posts/newsletter-018 !!

Huge thanks to all contributors and reviewers! :crab::crab::crab:
