### ISSUE TITLE
 Newsletter 20

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#531]
Feel free to suggest sections about any March rust gamedev news and updates!

If you want to help writing the newsletter:

- Grab some of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Mentions in brackets (like "🆓 **free** (@ozkriff?)") are just an invitation to write the corresponding section if you want, but anyone is free to take it.
- Write a short overview:
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter and run markdownlint, please.
  - Insert line breaks ([softbreak](https://spec.commonmark.org/0.29/#soft-line-breaks)) at 80 chars, please.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #336)
  - Mention this issue in your PR's description to link it all together.

------

Quoting @AngelOnFira from the last month's coordination issue:

> \<...>
> We're going to be transitioning to having authors or volunteers write about their own content, rather than the editing team doing it all at the end 100 This means if you want to see your work in the newsletter, you have to write it yourself! If you're not able to write about your work, feel free to comment and I can assign it free free. We're working on taking some of the load off the editing team where we can with this. Best to keep this sustainable!
>
> Also, we want to make sure contributing to the newsletter feels open to anyone who wants to write a section about their project. If you have anything you can write about, just add a comment to this issue and I'll add it to the todo list smile

------

## Current Schedule

The soft deadline for all section PRs is 2021.04.06.
Review and Release will take place on 2021.04~~.08~~ ~~.09~~ .10.

------

⚠️ [It was decided to try a shorter and more limited section format](https://github.com/rust-gamedev/rust-gamedev.github.io/issues/454): ⚠️

- Only one image (<300kb) or GIF (<2.5mb) before the text. With an optional caption and a mandatory alt text.
- All the (rendered) text should be under 1000 characters (including spaces and punctuation) and under 6 paragraphs (without any subsections, etc).
- No bold/italic/etc formatting - only links and one plain list without nesting per section (multiple lists are allowed if your project consists of multiple parts that aren't independent enough for their own sections).
- Third-person perspective.
- 80 chars per MD line and no other markdownlint warnings on CI.
- Only the following simple templates are allowed:

  <details>
    <summary>See the templates</summary>

    For games/apps/libs:

    ```md
    ### [Gamename]

    ![alt text](img)
    _optional image label_

    [Gamename] ([GitHub], [Discord], [Twitter]) by [@nickname]
    is ... {short project description in one sentence}.

    {An overview of the recent updates with links to more details}.

    _Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

    {md links block}
    ```

    For articles/videos/etc:

    ```md
    ### [Articlename]

    ![alt text](img)
    _optional image label_

    [@nickname] published an [article] about ...
    {overview what the resource is about}.

    _Discussions: [/r/rust_gamedev](link), [Twiter](link), [etc](link)_

    {md links block}
    ```

  </details>

_`CONTRIBUTING.md` isn't updated for this yet_.

## Current Structure & Status

If you have your own project that you want to write about, just make a comment on this issue!

(_I'll try to keep this updated_)

- [x] Meetup - ✔️ done by @AngelOnFira in #574
- [ ] Game Updates
  - [x] SM64JS ([1](https://reddit.com/r/rust_gamedev/comments/mi4h32/super_mario_64_javascript_port)) - ✔️ done by @Tarnadas in #558
  - [x] MineWars - ✔️ done by @jamadazi in #570
  - [ ] Recall Singularity ([1](https://twitter.com/RecallSingular1)) - 🆓 **free** (@tom-leys?)
  - [x] Theta Wave ([1](https://github.com/amethyst/theta-wave/releases/tag/v0.1.4), [2](https://reddit.com/r/rust/comments/m6a3yx/theta_wave_v014_foundations_update))  - ✔️ done by @cdsupina in #553
  - [ ] Demon Attack ([1](https://github.com/TanTanDev/rusty_demon_attack), [2](https://youtube.com/watch?v=Ymq35SIv9Gg)) - 🆓 **free** (@TanTanDev?)
  - [x] fishgame - ✔️ done by @not-fl3 in #572
  - [x] A/B Street ([1](https://twitter.com/CarlinoDustin), [2](https://reddit.com/r/abstreet)) - ✔️ done by @dabreegster in #542
  - [x] pGLOWrpg ([1](https://twitter.com/Roal_Yr)) - ✔️ done by @roalyr in #536
  - [x] Veloren v0.9 - ✔️ done by @AngelOnFira in #563
  - [x] Way of Rhea ([1](https://store.steampowered.com/app/1110620/Way_of_Rhea/), [2](https://store.steampowered.com/news/app/1110620/view/2985297497522422575), [3](https://twitter.com/AnthropicSt)) - ✔️ done by @MasonRemaley in #577
  - [x] Aladin Lite ([1](https://reddit.com/r/rust_gamedev/comments/lyegtv/aladin_lite_an_astronomical_surveys_visualizer)) - ✔️ done by @bmatthieu3 in #560
  - [x] Egregoria v0.8 ([1](https://douady.paris/blog/egregoria_8.html)) - ✔️ done by @Uriopass in #539
  - [x] Gargoyle's Quest remake ([1](https://github.com/ShamylZakariya/Platformer), [2](https://reddit.com/r/rust_gamedev/comments/m730kz/i_made_gargoyles_quest_in_rust_using_wgpu)) - ✔️ done by @ShamylZakariya in #547
  - [ ] Shotcaller ([1](https://reddit.com/r/rust_gamedev/comments/m1bm0o/shotcaller_microinput_for_bot_scripts)) - 🆓 **free** (@erlend-sh?)
  - [x] Harvest Hero - ✔️ done by @Bombfuse in #555
  - [x] 7DRL Disguiser ([1](https://mcneja.github.io/disguiser), [2](https://reddit.com/r/rust_gamedev/comments/m5tjbs/7drl_in_rust), [3](http://playtechs.blogspot.com/search/label/2021-7drl)) - ✔️ done by @ozkriff in #579
  - [x] 7DRL orbital-decay ([1](https://gridbugs.itch.io/orbital-decay)) - ✔️ done by @stevebob in #535
  - [x] 7DRL secbot ([1](https://thebracket.itch.io/secbot), [2](https://twitter.com/herberticus/status/1370149132933926914), [3](https://rust-linz.at/)) - ✔️ done by @ozkriff in #579
  - [x] rusty-bomber ([1](https://rgripper.github.io/rusty-bomber/), [2](https://github.com/rgripper/rusty-bomber), [3](https://github.com/rgripper/rusty-bomber/blob/master/blog/blog.md)) - ✔️ done by @ozkriff in #579
  - [x] Bounty Bros - ✔️ done by @zicklag in #551
  - [x] Station Iapetus - ✔️ done by @mrDIMAS in #564
  - [x] Stellary 2 - ✔️ done by @dezajno in #546
  - [x] Portal Explorer ([1](https://twitter.com/optozorax/status/1372318558584242178)) - ✔️ done by @optozorax in #561
  - [x] Name Needed - ✔️ done by @DomWilliams0 in #566
  - [x] Outer Wonders ([1](https://utopixel.games/en/blog/)) - ✔️ done by @ozkriff in #579
- [ ] Learning Material Updates
  - [x] Robo Instructus article ([1](https://builtin.com/software-engineering-perspectives/rust-puzzle-game)) - ✔️ done by @ozkriff in #580
  - [x] Writing a 3D Shooter using rg3d ([1](https://rg3d.rs/tutorials/2021/03/05/tutorial1.html), [2](https://rg3d.rs/tutorials/2021/03/09/tutorial2.html), [3](https://rg3d.rs/tutorials/2021/03/11/tutorial3.html)) - ✔️ done by @ozkriff in #580
  - [x] Using tests to speed up your feedback loop ([1](https://reddit.com/r/rust_gamedev/comments/man8u1/using_tests_to_speed_up_your_feedback_loop)) - ✔️ done by @ozkriff in #580
  - [x] Writing a tiny Entity Component System in Rust ([1](https://ianjk.com/ecs-in-rust/), [2](https://reddit.com/r/rust/comments/m88ywa/tutorial_writing_a_tiny_entity_component_system)) - ✔️ done by @kettle11 in #557
  - [ ] Writing Pong in Rust for my OS Written in Rust ([1](https://blog.stephenmarz.com/2021/02/22/writing-pong-in-rust/), [2](https://reddit.com/r/rust/comments/m6i5oa/writing_pong_in_rust_for_my_os_written_in_rust)) - 🆓 **free** (@sgmarz?)
  - [x] Reverse-Engineering NES Tetris to add Hard Drop ([1](https://reddit.com/r/rust/comments/ma6jqz/using_a_rust_dsl_to_add_hard_drop_to_nes_tetris/)) - ✔️ done by @stevebob in #537
  - [x] bevy_game_template ([1](https://github.com/NiklasEi/bevy_game_template)) - ✔️ done by @NiklasEi in #548
  - [x] Bevy Cheatbook - ✔️ done by @jamadazi in #554
- [x] Engine Updates
  - [x] Tetra v0.6.1/0.6.2 - ✔️ done by @17cupsofcoffee in #544
  - [x] Emerald ([1](https://twitter.com/bombfuse_dev/status/1372400013003816965), [2](https://github.com/Bombfuse/emerald)) - ✔️ done by @Bombfuse in #532
  - [x] Starframe - ✔️ done by @MoleTrooper in #538
  - [x] rg3d & rusty-editor - ✔️ done by @mrDIMAS in #564
  - [x] Oxygengine - ✔️ done by @PsichiX in #575
  - [x] bevy v0.5 - ✔️ done by @cart in #573
- [ ] Library & Tooling Updates
  - [x] genesis ([1](https://crates.io/crates/genesis/0.1.1), [2](https://github.com/StygianLightning/genesis)) - ✔️ done by @ozkriff in #582
  - [ ] Mun - 🚧 WIP by @Wodann
  - [x] Planck ECS ([1](https://jojolepro.com/blog/2021-01-13_planck_ecs/), [2](https://reddit.com/r/rust/comments/m73ema/yet_another_ecs_library_except_much_safer), [3](https://reddit.com/r/rust/comments/meiahi/planck_ecs_is_now_using_apache_20/)) - ✔️ done by @jojolepro in #545
  - [x] Shipyard v0.5 ([1](https://users.rust-lang.org/t/shipyard-0-5-release/57203)) - ✔️ done by @ozkriff in #582
  - [x] Hecs v0.5 ([1](https://github.com/Ralith/hecs)) - ✔️ done by @Ralith in #569
  - [x] building-blocks v0.6 ([1](https://github.com/bonsairobo/building-blocks/releases/tag/v0.6.0)) - ✔️ done by @bonsairobo in #571
  - [x] Quinn ([1](https://github.com/quinn-rs/quinn/releases/tag/0.7.0)) - ✔️ done by @Ralith in #568
  - [x] WhatTheFrame - ✔️ done by @JMS55 in #541
  - [ ] switchyard v0.2 ([1](https://github.com/BVE-Reborn/switchyard)) - 🆓 **free** (@cwfitzgerald?)
  - [x] rkyv is faster ([1](https://davidkoloski.me/blog/rkyv-is-faster-than/), [2](https://reddit.com/r/rust/comments/m2yxb1/rkyv_is_faster_than_bincode_capnp_cbor)) - ✔️ done by @djkoloski in #552
  - [ ] smol-rgb ([1](https://github.com/sanbox-irl/smol-rgb)) - 🆓 **free** (@sanbox-irl?)
  - [ ] colorgrad ([1](https://github.com/mazznoer/colorgrad-rs), [2](https://reddit.com/r/rust/comments/lgyuuj/announcing_colorgrad_v030_rust_color_scales))  - 🆓 **free** (@mazznoer?)
  - [x] Kira v0.5 ([1](https://twitter.com/tesselode/status/1368984205947006976)) - ✔️ done by @tesselode in #556
  - [x] nakama-rs - ✔️ done by @not-fl3 in #572
  - [ ] wasm_plugin_host/wasm_plugin_guest ([1](https://crates.io/crates/wasm_plugin_guest), [2](https://crates.io/crates/wasm_plugin_host))  - 🆓 **free** (@alec-deason?)
  - [x] smaa-rs ([1](https://github.com/fintelia/smaa-rs)) - ✔️ done by @fintelia in #567
  - [x] egui-macroquad ([1](https://crates.io/crates/egui-macroquad), [2](https://optozorax.github.io/egui-macroquad/)) - ✔️ done by @optozorax in #562
  - [ ] iced v0.3 ([1](https://www.reddit.com/r/rust/comments/mhg5ep/iced_03_released/)) - 🚧 WIP by @hecrj
  - [x] rust-gpu v0.3 ([1](https://www.reddit.com/r/rust/comments/lxpcc2/announcing_rustgpu_v03/), [2](https://twitter.com/repi/status/1365256477569667075)) - ✔️ done by @ozkriff in #582
  - [x] FemtoVG - ✔️ done by @adamnemecek in #549
  - [ ] three-d ([1](https://twitter.com/AsgerNyman/status/1369723410222301184)) - 🆓 **free** (@asny?)
  - [x] rafx - ✔️ done by @aclysma in #543
  - [x] wgpu&naga ([1](https://reddit.com/r/rust_gamedev/comments/mgvd8d/last_big_wgpurs_example_shaders_are_fully_ported), [2](https://mozillagfx.wordpress.com/2021/03/10/webgpu-progress/)) - ✔️ done by @kvark in #533
  - [x] Kajiya - ✔️ done @h3r2tic in #565
  - [x] raui v0.28 ([1](https://github.com/PsichiX/raui)) - ✔️ done by @PsichiX in #575
  - [x] Bevy Retro - ✔️ done @zicklag in #550
  - [x] Bitmapflow ([1](https://github.com/Bauxitedev/bitmapflow), [2](https://reddit.com/r/rust/comments/mdpuyo/introducing_bitmapflow_a_tool_to_generate)) - ✔️ done by @Bauxitedev in #559
  - [x] Graphite - ✔️ done by @Keavon in #576

Final steps:

- [x] final review - by everyone
- [x] publish - by @ozkriff
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev - by @ozkriff
- [x] add comment links - by @ozkriff
- [x] add a draft of the 21th newsletter - by @ozkriff

_Editors_: @ozkriff @17cupsofcoffee @AngelOnFira

**Comment by Bombfuse** [comment]
got emerald 👍

**Comment by Uriopass** [comment]
I'll take Egregoria :)

**Comment by MoleTrooper** [comment]
I'd like to mention starframe's [recent physics progress](https://twitter.com/moletrooper/status/1360723470414450688) and the [blog post](https://moletrooper.github.io/blog/2021/03/starframe-devlog-constraints/) about it published the other day :wave:

**Comment by Lokathor** [comment]
I don't even remember what's new in the GL crates that was an entire months ago. It's better than before somehow, I'm sure.

**Comment by Tarnadas** [comment]
I’d like to write about [sm64js](https://www.reddit.com/r/rust_gamedev/comments/mi4h32/super_mario_64_javascript_port/).
I know that it hasn’t been posted in March, but I hope this is still okay. Since we’re having a stress test in April, this would be really helpful

**Comment by dabreegster** [comment]
I'll write about A/B Street

**Comment by djkoloski** [comment]
I'll write about "rkyv is faster than {...}". 🙂

**Comment by expenses** [comment]
My project isn't a game as such as I don't think I would have much to contribute anywa

**Comment by bonsairobo** [comment]
I'll write about building-blocks v0.6.0.

**Comment by bmatthieu3** [comment]
I want to write about Aladin Lite

**Comment by NiklasEi** [comment]
Would a [template repository for bevy games](https://github.com/NiklasEi/bevy_game_template) fit in here (maybe under Learning materials)?

**Comment by jakmeier** [comment]
Hey, thanks for putting Paddlers on the list again! Nothing new released or published this month, though. (0.2.1 was released at the end of February)

**Comment by kettle11** [comment]
>  Writing a tiny Entity Component System in Rust (1, 2) - 🆓 free (@kettle11?)
I'll claim this one. Thanks!

**Comment by optozorax** [comment]
I will take `egui-macroquad` and `Portal Explorer`.

**Comment by stevebob** [comment]
I'll write about [Reverse-Engineering NES Tetris to add Hard Drop](https://reddit.com/r/rust/comments/ma6jqz/using_a_rust_dsl_to_add_hard_drop_to_nes_tetris/).
I'll also write about [Orbital Decay](https://gridbugs.itch.io/orbital-decay) which is a 7 Day Roguelike game jam game I made in rust.

**Comment by dezajno** [comment]
I'd like to write about some **Stellary 2** updates :)

**Comment by Wodann** [comment]
I'll take Mun's update

**Comment by sanbox-irl** [comment]
No imgui-rs update this month! Thanks though :)

**Comment by roalyr** [comment]
Will do pGLOWrpg.

**Comment by Keavon** [comment]
I'll be submitting a section for Graphite development progress (probably relevant under the *Libraries & Tooling Updates* section, unless we renamed *Game Updates* to *Game/App Updates*.

**Comment by PsichiX** [comment]
i have a question - if i publish oxygengine + raui update today does it counts as entry for this month newsletter or i have to wait for next month?
also i take raui update waiting for me here :D

**Comment by ShamylZakariya** [comment]
I'd love to do a writeup on my Gargoyle's Quest build; that being said I've never contributed here before, I don't know what the procedure is - where do I submit a writeup?

**Comment by 17cupsofcoffee** [comment]
@ShamylZakariya Ideally, submit it as a pull request to the Game Updates section - via [the web editor](https://github.com/rust-gamedev/rust-gamedev.github.io/edit/source/content/posts/newsletter-020/index.md) is fine, if you don't want to do it locally :)

**Comment by termhn** [comment]
Hi, the 0.8 update of ultraviolet is quite small, just some incremental changes so I don't think writing much about it is worth it :)

**Comment by JMS55** [comment]
I'll be writing about [WhatTheFrame](https://github.com/JMS55/whattheframe), the profiler + GUI I've been working on this month.

**Comment by ozkriff** [comment]
> I don't even remember what's new in the GL crates that was an entire months ago. It's better than before somehow, I'm sure.

@Lokathor :ok_hand: removed gl33 from this issue's plan. Would you like to write something about Yacurses v0.2.4?

> My project isn't a game as such as I don't think I would have much to contribute anyway

@expenses :ok_hand: removed dune_scene from the plan.

> Would a template repository for bevy games fit in here (maybe under Learning materials)?

@NiklasEi sure! "Learning materials" sounds fit.

> 0.2.1 was released at the end of February

@jakmeier oh, right!

> I'll be submitting a section for Graphite development progress (probably relevant under the Libraries & Tooling Updates section, unless we renamed Game Updates to Game/App Updates.

@Keavon added to Libraries & Tooling 

> i have a question - if i publish oxygengine + raui update today does it counts as entry for this month newsletter or i have to wait for next month?

@PsichiX if the update describes the work you've been doing through March - it counts :)

> I'd love to do a writeup on my Gargoyle's Quest build; that being said I've never contributed here before, I don't know what the procedure is - where do I submit a writeup? Sounds like I should just fill out the template - can I submit it here in the comments?

@ShamylZakariya as 17cups said a PR to the [draft](https://github.com/rust-gamedev/rust-gamedev.github.io/blob/source/content/posts/newsletter-020/index.md) is a preferred workflow but posting your section as a comment here is fine too.

> Hi, the 0.8 update of ultraviolet is quite small, just some incremental changes so I don't think writing much about it is worth it :)

@termhn ok, removed!

**Comment by Bauxitedev** [comment]
I'd like to work on the Bitmapflow section.

**Comment by jojolepro** [comment]
Taking Planck ECS! :hearts:

**Comment by cdsupina** [comment]
I'll try to have a PR for Theta Wave done by the end of today!

**Comment by jamadazi** [comment]
What order are games to be listed in, on the public newsletter? The order of the listings could really affect which projects get most visibility...

**Comment by zicklag** [comment]
@ozkriff sorry I'm not on Discord/Telegram so I can't DM you for this question: I have three different projects to post about this month, a Bevy plugin, a game engine built on top of Bevy and that plugin, and the Bounty Bros. game. Their all built on top of each-other so they could go into one section, but should they be separate?

Also if they are separate, should each be in its own PR?

**Comment by cwfitzgerald** [comment]
I'll write about rend3 next time around, there's a major refactor coming shortly that I would like to be included.

**Comment by ozkriff** [comment]
> What order are games to be listed in, on the public newsletter? The order of the listings could really affect which projects get most visibility...

@jamadazi we don't have strict ordering for games but I'm usually trying to show new big games first. Maybe we should have a more explicit policy here, yeah.

> I have three different projects to post about this month, a Bevy plugin, a game engine built on top of Bevy and that plugin, and the Bounty Bros. game. They're all built on top of each-other so they could go into one section, but should they be separate?
> Also if they are separate, should each be in its own PR?

@zicklag separate sections sound good. although if the plugin's section is small it may make sense to merge it into the engine's one.

> I'll write about rend3 next time around, there's a major refactor coming shortly that I would like to be included.

@cwfitzgerald ok! removed from the current plan :)

**Comment by ozkriff** [comment]
:warning: A reminder that the editors [won't write _all_ the untaken sections themselves](https://github.com/rust-gamedev/rust-gamedev.github.io/issues/454) anymore so if you want to make sure that something will be mentioned - you're encouraged to volunteer and grab these sections. :)

There are 26 free sections atm.

**Comment by fintelia** [comment]
I can write up something for smaa-rs

**Comment by Lokathor** [comment]
@ozkriff 0.2.4 of yacurses is small enough that i don't even remember what it does. just tiny bugfixes. you should *still* program ascii roguelikes of course, but i don't think it needs an annoucnement.

**Comment by Bombfuse** [comment]
Adding section for Harvest Hero 👍

**Comment by tesselode** [comment]
i'll take kira

**Comment by Ralith** [comment]
I'll do something for hecs and quinn

**Comment by DomWilliams0** [comment]
Can I please add a section plugging my game/engine and dev logs? https://github.com/DomWilliams0/name-needed

**Comment by ozkriff** [comment]
@DomWilliams0 sure!

**Comment by hecrj** [comment]
I can write something for `iced` in the next hours.

**Comment by alexheretic** [comment]
Thanks for considering that Robo Instructus article. I don't think I'll have time to raise a pr this time, so feel free to leave it out.

**Comment by ozkriff** [comment]
@hecrj that would be great!

@alexheretic :ok_hand:  that's a cool article though, I'll try to write some summary myself :)

**Comment by ozkriff** [comment]
We've passed the soft deadline - pingning @PsichiX @Wodann @Keavon, how're your WIP sections going? :)

**Comment by Keavon** [comment]
Wasn't sure about the time zones and how much time I could squeak by :)

We finished up a big milestone last night so I've been writing the Graphite section on and off this morning. It's surprisingly hard to condense a lot of details into under 1k characters. I'm aiming to have it done within the next couple hours.

**Comment by ozkriff** [comment]
@Keavon yeah, writing a good overview is hard sometimes.

> within the next couple hours

It's likely that the final draft will be ready in something like 20 hrs so there's no need to rush that much :)

**Comment by ozkriff** [comment]
Grabbing "Disguiser", "secbot", "rusty-bomber", "Outer Wonders", and "Robo Instructus article".

There're ~15 more free sections if anyone wants to help.

**Comment by PsichiX** [comment]
Oxygengine & RAUI updates pushed :D

**Comment by ozkriff** [comment]
Taking "Writing a 3D Shooter using rg3d" and "Using tests to speed up your feedback loop" learning sections.

Some cool library stuff is also not written, so going to take a few more library&tools sections later today and will publish the final draft closer to the evening (in my timezone).

**Comment by ozkriff** [comment]
Taking the last bunch of sections: genesis, Shipyard, rust-gpu.

**Comment by Lokathor** [comment]
* The [gba](https://github.com/rust-console/gba) crate was updated to 0.4! It's using the new `thumbv4-none-eabi` target, and has an overall simpler build process than before. The project is still a work in progress, but if you've wanted to try an embedded experience this is an easy way to test the waters. No hardware required! Compiled binaries can be run in a GBA emulator just fine.

**Comment by ozkriff** [comment]
Final PR - https://github.com/rust-gamedev/rust-gamedev.github.io/pull/583 - everyone is invited to review

**Comment by ozkriff** [comment]
:tada:  https://rust-gamedev.github.io/posts/newsletter-020

As always, huge thanks to all editors, contributors, and reviewers! :crab::crab::crab:
