### ISSUE TITLE
Newsletter 7: Coordination/Tracking

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#64]
~~I'm _hoping_ to publish the newsletter on 2019.03.03.~~
~~The newsletter will be published on 2019.03.04.~~
The newsletter will be published on 2019.03.**05** for sure.

If you want to help writing the newsletter:

- grab one of the "**free**" sections by leaving a comment like "I'd like to work on {section_name}".
- Write it :)
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter, please.
  - Hard-wrap at 80 chars, please.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR _to the `source` branch_ (example: #49)
  - Mention this issue in your PR's description to link it all together.

Current status/structure (I'll try to keep this updated):

- [x] Survey Results - ✔️ done by @ozkriff in #74
- [x] New Discrod Rust Gamedev Server - ✔️ done by @ozkriff in #74
- [x] AWGY Updates - ✔️ done by @17cupsofcoffee in #67
- [x] RustTallinn - ✔️ done by @ozkriff in #74
- [x] Game Updates
  - [x] Oxidator - ✔️ done by @ozkriff in #75
  - [x] Univer City 1.0 - ✔️ done by @ozkriff in #75
  - [x] Rusty Shooter - ✔️ done by @mrDIMAS in #63
  - [x] Veloren - ✔️ done by @AngelOnFira in #71
  - [x] Colony - ✔️ done by @ozkriff in #74
  - [x] Garden - ✔️ done by @ozkriff in #74
  - [x] Dwarf World - ✔️ done by @ozkriff in #75
  - [x] Way of Rhea - ✔️ done by @ozkriff in #75
  - [x] Antorum ([1](https://dooskington.com/dev-log/18)) - ✔️ done by @AngelOnFira in #65
  - [x] Noodle Cat ([1](https://twitter.com/Fryer00/status/1225829271597395971), [2](https://twitter.com/Fryer00/status/1227327016380305415), [3](https://twitter.com/Fryer00/status/1232181181690654720)) - ✔️ done by @ozkriff in #75
  - [x] Akigi ([1](https://devjournal.akigi.com/february-2020/2020-02-09.html), [2](https://devjournal.akigi.com/february-2020/2020-02-16.html), [3](https://devjournal.akigi.com/february-2020/055-2020-02-23.html)) - ✔️ done by @AngelOnFira in #70
  - [x] Scale ([1](http://douady.paris/blog/scale_2.html), [2](https://youtube.com/watch?v=nk6F42BQllU), [3](https://reddit.com/r/rust_gamedev/comments/f1egnd/scale_devblog_2), [4](https://youtube.com/watch?v=p18M6WdrQPM)) - ✔️ done by @Uriopass in #72
  - [x] Ultimate Scale ([1](https://reddit.com/r/rust_gamedev/comments/f3cll6/ultimate_scale_counting_modulo_three), [2](https://www.youtube.com/watch?v=hWbX9d8xc-k), [3](https://youtube.com/watch?v=IM3BRM_MZrE)) - ✔️ done by @Uriopass in #72
  - [x] Tennis Academy Dash - ✔️ done by @iolivia in #68
  - [x] Lonely Star ([1](https://17cupsofcoffee.itch.io/lonely-star), [2](https://twitter.com/17cupsofcoffee/status/1227676711069851648), [3](https://twitter.com/17cupsofcoffee/status/1217524602513055749) and [4](https://twitter.com/17cupsofcoffee/status/1219758851416895489)) - ✔️ done by @17cupsofcoffee in #66
  - [x] Will network design - ✔️ done by @azriel91 in #73
  - [x] Robo Instructus ([1](https://twitter.com/bigabgames/status/1228738913721835525), [2](https://twitter.com/bigabgames/status/1233187089782648833), [3](https://steamcommunity.com/games/1032170/announcements/)) - ✔️ done by @ozkriff in #79
  - [x] everpuzzle ([1](https://github.com/Skytrias/everpuzzle)) - ✔️ done by @Skytrias in #69
  - [x] Recall Singularity - ✔️ done by @ozkriff in #79
  - [x] Great China - ✔️ done by @ozkriff in #79
  - [x] pGLOWrpg - ✔️ done by @ozkriff in #79
  - [x] For the Quest - ✔️ done by @ozkriff in #79
  - [x] Grumpy Visitors - ✔️ done by @mvlabat in #82
- [x] Library & Tooling Updates
  - [x] Fix Your Time Step in Rust and GGEZ ([1](https://joetsoi.github.io/fix-your-timestep-rust-ggez)) - ✔️ done by @17cupsofcoffee in #83 
  - [x] savefile v0.5 ([1](https://reddit.com/r/rust/comments/eyxoao/savefile_050)) - ✔️ done by @PatrickHoward in #81
  - [x] specs v0.16 ([1](https://github.com/amethyst/specs/releases/tag/0.16.0)) - ✔️ done by @azriel91 in #73
  - [x] shipyard ([1](https://reddit.com/r/rust/comments/fbo8wf/shipyard_03_release)) - ✔️ done by @AngelOnFira in #78
  - [x] crow 0.3 ([1](https://reddit.com/r/rust/comments/f2wuwc/i_just_published_crow_03_a_pixel_perfect_2d), [2](https://github.com/lcnr/akari)) - ✔️ done by @AngelOnFira in #78
  - [x] patchwork ([1](https://github.com/RedSquirrelsNut/patchwork)) - ✔️ done by @AngelOnFira in #78
  - [x] KAS ([1](https://reddit.com/r/rust/comments/f97kgn/kas_gui_03)) - ✔️ done by @AngelOnFira in #78
  - [x] OXYGENGINE ([1](https://reddit.com/r/rust/comments/ez3h9h/oxygengine_added_support_for_nested_ui_widgets)) - ✔️ done by @PsichiX in #84
  - [x] image v0.23 ([1](https://reddit.com/r/rust/comments/f0vrj3/announcing_image_crate_v023)) - ✔️ done by @AngelOnFira in #78
  - [x] neovide - ✔️ done by @aclysma in #80
  - [x] gfx & wgpu - ✔️ done by @kvark/@ozkriff in #85
  - [x] miniquad - ✔️ done by @not-fl3/@ozkriff in #85
  - [x] This month in rustsim #9 ([1](https://www.rustsim.org/blog/2020/03/01/this-month-in-rustsim)) - ✔️ done by @ozkriff in #85
  - [x] weasel - ✔️ done by @ozkriff in #85
  - [x] RLTK & Roguelike Book - ✔️ done by @ozkriff in #85
  - [x] superluminal-perf-rs - ✔️ done by @ozkriff in #85
  - [x] riven - ✔️ done by @ozkriff in #85
  - [x] Rust on RG300 - ✔️ done by @ozkriff in #85
  - [x] glium 0.26 - ✔️ done by @ozkriff in #85
  - [x] luminance - ✔️ done by @ozkriff in #85
  - [x] pushrod - ✔️ done by @ozkriff in #85
- [x] Popular Workgroup Issues in Github - ✔️ done by @ozkriff in #85
- [x] Bonus - ✔️ done by @ozkriff in #85

TODOs:

- [x] final review
- [x] publish - ✔️ done by @ozkriff in @ozkriff #85
- [x] post on /r/rust, /r/rust_gamedv, /r/gamedev, URLO, twitter.com/rust_gamedev - @ozkriff
- [x] add comment links - @ozkriff
- [x] hard wrap everything - ✔️ done by @ozkriff in #88
- [x] PR with a draft of the 8 newsletter - ✔️ done by @ozkriff in #87

**Comment by 17cupsofcoffee** [comment]
Really like this format 😄 Hopefully it gets more people helping out.

I'll pick up writing the section for Lonely Star, if that's okay?

**Comment by AngelOnFira** [comment]
I'll be doing Veloren, and I'll take another game update, say Antorum

**Comment by AngelOnFira** [comment]
Taking Akigi

**Comment by Skytrias** [comment]
I'd like to add a section about everpuzzle https://github.com/Skytrias/everpuzzle
even though i probably won't be able to release version 0.2 till the newsletter comes out i'd like to show the project of

**Comment by 17cupsofcoffee** [comment]
As discussed on Discord, I'll also pick up the section about the AWGY updates 🙂

**Comment by azriel91** [comment]
Heya, I'll write something for the `specs` update, and add a link to my game's "Designing Network Play" blog post.

**Comment by Uriopass** [comment]
I'd like to work on the `Scale` and `Ultimate Scale` updates.

**Comment by PatrickHoward** [comment]
Hi! I can take on the savefile crate!

**Comment by ozkriff** [comment]
Taking "Noodle Cat"

**Comment by ozkriff** [comment]
Taking Robo.Instructus

**Comment by AngelOnFira** [comment]
I've got some free time, so I'll grab

- shipyard 
- crow 0.3 
- patchwork 
- KAS 
- OXYGENGINE 
- image v0.23

**Comment by AngelOnFira** [comment]
@ozkriff I came across this while looking at crow. Might be worth adding?

https://github.com/lcnr/akari

**Comment by ozkriff** [comment]
@AngelOnFira yeah. I think it's better to add this as a subsection of the "crow v0.3" section.

**Comment by ozkriff** [comment]
Moved the planned release day:

> ~~I'm _hoping_ to publish the newsletter on 2019.03.03.~~
> The newsletter will be published on 2019.03.**04**.

**Comment by 17cupsofcoffee** [comment]
I can pick up 'Fix Your Time Step in Rust and GGEZ' in a few hours, if no-one else wants it? Then all the items will be accounted for :)

**Comment by ozkriff** [comment]
The final content PR is ready - #85 (_"Newsletter 7"_) - everyone is invited to review!

:timer_clock: Hope to merge this in a few hours if there're no objections!

**Comment by ozkriff** [comment]
The newsletter is out! :tada: 

https://rust-gamedev.github.io/posts/newsletter-007 ([twitter](https://twitter.com/rust_gamedev/status/1235645370350227456), [/r/rust](https://www.reddit.com/r/rust/comments/fe03sb/this_month_in_rust_gamedev_7_february_2020/))

Many thanks to all contributors and reviewers! 🦀

**Comment by Wodann** [comment]
Well done on the newsletter, everyone. I think the tracking issue worked really well, @ozkriff. A good idea! 👏

**Comment by Skytrias** [comment]
yea good job, everyone. 

will every project always have to reintroduce itself each newsletter? takes a few paragraphs per project

**Comment by PsichiX** [comment]
i think we could make it somethink like this: if project got introduced in previous newsletter, one could add a link to that project note.

Good idea?

**Comment by ozkriff** [comment]
> will every project always have to reintroduce itself each newsletter? takes a few paragraphs per project

I've been trying to use big introductions only for projects that weren't mentioned in the newsletter before, otherwise use only a quick one-line reminder.

**Comment by ozkriff** [comment]
Next! #89 (_"Newsletter 8: Coordination/Tracking"_)
