### ISSUE TITLE
Newsletter 8: Coordination/Tracking

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#89]
If you want to help writing the newsletter:

- grab one of the "🆓 **free**" sections by leaving a comment like "I'd like to work on {section\_name\_1} and {section\_name\_2}".
- Write it :)
  - Use provided links as a starting point.
  - Try to maintain a consistent style with the rest of the newsletter, please.
  - Hard-wrap at 80 chars, please.
  - Use third-person pronouns even if you write about your project updates.
  - DM me on Discord or Telegram if there're any questions.
- Send a PR *to the `source` branch* (example: #75)
  - Mention this issue in your PR's description to link it all together.

Feel free to suggest sections.

Current structure/status (I'll try to keep this updated):

- [x] LDN Virtual Talks April 2020 (GameDev Special) ([1](https://www.meetup.com/Rust-London-User-Group/events/269357779/)) - ✔️ done by @ozkriff
- [x] spreading the word note - ✔️ done by @ozkriff
- [x] Game Updates
  - [x] Veloren ([1](https://veloren.net/)) - ✔️ done by @AngelOnFira in #108
  - [x] Urban Gift ([1](https://twitter.com/UrbanGiftGame/status/1233835733791711232)) - ✔️ done by @ozkriff in #98
  - [x] Will: Online Play + Open Source ([1](https://azriel.im/will/2020/03/13/join-me/)) - ✔️ done by by @azriel91 in #94
  - [x] Tennis Academy Dash ([1](https://twitter.com/oliviff/status/1243972292750819329), [2](https://twitter.com/oliviff/status/1238978081429299201)) - ✔️ done by @ozkriff in #100
  - [x] Colony Genesis ([1](https://nativesystems.itch.io/colony/devlog/129507/colony-genesis-v101-alpha), [2](https://nativesystems.itch.io/colony/devlog/132469/colony-genesis-v102-alpha)) - ✔️ done by @ozkriff in #98
  - [x] slime99 ([1](https://gridbugs.itch.io/slime99)) - ✔️ done by @stevebob in #97
  - [x] Coffe Junk Studio: "Sphere Game" and "Helix Repair" ([1](https://twitter.com/CoffeJunkStudio/status/1239235545743663107), [2](https://twitter.com/CoffeJunkStudio/status/1243171134838845440)) - ✔️ done by @ozkriff in #100
  - [x] Garden ([1](https://twitter.com/logicsoup/status/1246774418233348096), [2](https://cyberplant.xyz/posts/march/)) - ✔️ done by @ozkriff
  - [x] Akigi ([1](https://devjournal.akigi.com/)) - ✔️ done by @ozkriff in #100
  - [x] Zemeroth ([1](https://twitter.com/ozkriff/status/1241718003470917635)) - ✔️ done by @ozkriff in #104
  - [x] Ascension 2 ([1](https://outkine.itch.io/ascension-2), [2](https://github.com/outkine/ascension-rust)) - ✔️ done by @ozkriff in #98
  - [x] For the Quest ([1](https://twitter.com/seratonik/status/1234342701190934530), [2](https://twitter.com/seratonik/status/1236882251415085057), [3](https://twitter.com/seratonik/status/1241466121477185536), [4](https://twitter.com/seratonik/status/1241916597775650817)) - ✔️ done by @seratonik in #96
  - [x] pGLOWrpg ([1](https://twitter.com/Roal_Yr/status/1234919130756767744), [2](https://twitter.com/Roal_Yr/status/1236003795265519616), [3](https://twitter.com/Roal_Yr/status/1236033070152798210), [4](https://twitter.com/Roal_Yr/status/1236268367968964610), [5](https://twitter.com/Roal_Yr/status/1239930909857644554), [6](https://twitter.com/Roal_Yr/status/1241671799236104192), [7](https://twitter.com/Roal_Yr/status/1242824451449856004)) - ✔️ done by @ozkriff in #98
  - [x] DynaMaze ([1](https://twitter.com/boring_cactus/status/1239387422082748416), [2](https://github.com/boringcactus/dynamaze), [3](https://boringcactus.itch.io/dynamaze)) - ✔️ done by by @boringcactus in #91
  - [x] Realm.One ([1](https://www.reddit.com/r/rust_gamedev/comments/ffmzr6/the_amethyst_engine_rust_networking_and_ecs_design/), [2](https://www.reddit.com/r/rust_gamedev/comments/friwse/game_development_in_rust_monsters_and_ai/)) - ✔️ done by @ozkriff in #107
- [x] Library & Tooling Updates
  - [x] rustsim ([1](https://rustsim.org/blog/2020/04/01/this-month-in-rustsim/), [2](https://www.rustsim.org/blog/2020/03/23/simd-aosoa-in-nalgebra/), [2](https://www.reddit.com/r/rust/comments/fnt1ru/simd_arrayofstructuresofarrays_in_nalgebra_and/)) - ✔️ done by @ozkriff in #103
  - [x] "Quest Engine P2: Deploying Rust app on Android" ([1](https://krupitskas.github.io/posts/quest-dev-part-2/)) - ✔️ done by @17cupsofcoffee in #90
  - [x] const-tweaker ([1](https://www.reddit.com/r/rust_gamedev/comments/fl7593/announcing_consttweaker_change_your_constants/)) - ✔️ done by @17cupsofcoffee in #90
  - [x] assets_manager ([1](https://www.reddit.com/r/rust_gamedev/comments/foywc6/announcing_assets_manager_conveniently_load_store/)) - ✔️ done by @17cupsofcoffee in #90
  - [x] netstack ([1](https://github.com/Vengarioth/netstack), [2](https://twitter.com/vengarioth/status/1242560964685451266)) - ✔️ done by @PatrickHoward
  - [x] bracket-lib & roguelike book ([1](https://www.reddit.com/r/rust_gamedev/comments/fevutz/bracketlib_work_week_of_372020_virtual_consoles/), [2](https://www.reddit.com/r/rust_gamedev/comments/fiij20/bracketlib_development_week_of_3142020_crosspost/), [3](https://bracketproductions.com/posts/ss/ss301/), [4](https://bracketproductions.com/posts/ss/ss302/)) - ✔️ done by @ozkriff in #103
  - [x] miniquad ([1](https://twitter.com/fedor_games/status/1234696812541489158), [2](https://twitter.com/fedor_games/status/1241616794114232321)) - ✔️ done by @not-fl3 in #105
  - [x] gfx/wgpu ([1](https://reddit.com/r/rust/comments/fnq64x/gfxhal05_is_released)) - ✔️ done by @kvark in #92
  - [x] Nannou ([1](https://nannou.cc/posts/nannou_v0.13)) - ✔️ done by @ozkriff in #100
  - [x] three-d ([1](https://asny.github.io/three-d), [2](https://github.com/asny/three-d)) - ✔️ done by @asny in #93
  - [x] Oxygengine ([1](https://twitter.com/PsichiX/status/1234795769485516800), [2](https://twitter.com/PsichiX/status/1243380190752813064), [3](https://twitter.com/PsichiX/status/1235036397763014656), [4](https://reddit.com/r/rust_gamedev/comments/fe57s0/oxygengine_development_progress_tracker)) - ✔️ done by @PsichiX in #106
  - [x] Amethyst ([1](https://twitter.com/AmethystEngine/status/1238725811672317953), [2](https://amethyst.rs/posts/release-0-15-0), [3](https://community.amethyst.rs/t/wasm-effort/1336), [4](https://community.amethyst.rs/t/atelier-legion-integration-demo/1352), [5](https://twitter.com/ToferC/status/1243361926786080768)) - ✔️ done by @azriel91 in #94
  - [x] ash ✔️ done by @msiglreith in #99
  - [x] rectangle-pack ([1](https://reddit.com/r/rust/comments/ffmqhc/rectanglepack_a_bin_packer_designed_to_conform_to)) - ✔️ done by @PatrickHoward in #101
  - [x] Mun ([1](https://mun-lang.org/blog/2020/03/10/this-month-february/)) - ✔️ done by @Wodann in #95
- [x] Popular Workgroup Issues in Github - ✔️ done by @ozkriff in #104
- [x] Bonus - ✔️ done by @ozkriff in #104

Final steps:

- [x] final review - everyone
- [x] publish - @ozkriff
- [x] post on /r/rust, /r/rust\_gamedv, /r/gamedev, URLO, twitter.com/rust\_gamedev - @ozkriff
- [x] add comment links - @ozkriff
- [ ] add a draft of the 9 newsletter - @ozkriff

**Comment by 17cupsofcoffee** [comment]
Since their authors aren't tagged, I'll pick up:

* Quest Engine Part 2: Deploying Rust app on android
* const-tweaker 
* assets_manager

I would also pick up netstack, but I don't fully understand what it does 😆 Networking is not my forte.

**Comment by PatrickHoward** [comment]
I’ll take on net stack and rectangle pack!

**Comment by Wodann** [comment]
I generally prefer not to engage in self-promotion, but I'd like to take on adding the [This month in Mun - February 2020](https://mun-lang.org/blog/2020/03/10/this-month-february/) blogpost - since it has been part of the newsletter.

**Comment by asny** [comment]
I'll take three-d as suggested.

**Comment by boringcactus** [comment]
I'll write up something for DynaMaze

**Comment by Machine-Hum** [comment]
I'll write up something on realm.one, topic two please! :) Do you have a length suggestion?

**Comment by ozkriff** [comment]
@Machine-Hum not sure, but a few paragraphs are usually enough to overview the updates.

**Comment by seratonik** [comment]
I'll take on the For The Quest section :)

**Comment by azriel91** [comment]
I will take Will, and me shall take Amethyst.

(yes I tried :slightly_smiling_face:)

**Comment by ozkriff** [comment]
Taking Urban Gift, Colony Genesis, Ascension 2, and pGLOWrpg sections.

**Comment by stevebob** [comment]
I will take slime99

**Comment by ozkriff** [comment]
Taking Sphere Game, Helix Repair, Akigi, and Nannou

**Comment by a1phyr** [comment]
Hi ! Author of `assets_manager` here.
I plan to release a new version with hot-reloading tonight. Is there a deadline for this to include this in the newsletter ?

I'll make a PR to include it when it is released

**Comment by ozkriff** [comment]
@a1phyr hey! Though the newsletter will be posted almost a week later, it's supposed to be a Match issue that covers only what happened in that month. News about your new release are supposed to be included in the 9th newsletter.

**Comment by ozkriff** [comment]
Taking rustsim and bracket-lib.

**Comment by ozkriff** [comment]
It'd be great to release the newsletter today in 5-8 hrs.

@AngelOnFira @not-fl3 @PatrickHoward @Machine-Hum @PsichiX, how're your sections going?

**Comment by ozkriff** [comment]
The final PR!  #109 (_"Newsletter 8"_) - everyone is invited to review.

:timer_clock: Hope to merge this today +- at 15:00 UTC (in six hrs from now).

**Comment by ozkriff** [comment]
https://rust-gamedev.github.io/posts/newsletter-008

Many thanks to all contributors and reviewers!

**Comment by ozkriff** [comment]
Next: #111 (_"Newsletter 9: Coordination/Tracking"_)
